### PR TITLE
Resolving KW issue with SoftwareSerial destructor

### PR DESCRIPTION
**Pull request by bbaltz505**
Class has virtual functions inherited from a base class, but its destructor is not virtual and not empty

### CODE REVIEW

**Comment by bbaltz505** [comment]
@bigdinotech please review

**Comment by bigdinotech** [comment]
@bbaltz505 @calvinatintel looks good to me.

**Comment by calvinatintel** [comment]
Merged in by mistake. I've reverted master to the previous commit but it doesn't seem like the PR reopens automatically. I'll merge in again.

**Comment by calvinatintel** [comment]
Merged

**Pull request merged**
