### PR TITLE
README.md: clean up and add "support" section

### PR DESCRIPTION
**Pull request by eriknyquist**
Break long lines to be <= 80 chars, where possible, and
add a new section to guide users to the appropriate place
for support (Arduino forum for product support, issue
tracker for bugs & features).

### CODE REVIEW

**Comment by calvinatintel** [comment]
Doesn't seem like the 80 char line break applies to `.md`?

**Comment by eriknyquist** [comment]
No, maybe it doesn't, but it sure looks nicer in a text editor that way :)

**Comment by calvinatintel** [comment]
[Approved](http://i.imgur.com/rK3TdJx.gif)

**Comment by eriknyquist** [comment]
yay, my first 101 commit...

**Pull request merged**
