### PR TITLE
Added Eddystone-URL support

### PR DESCRIPTION
**Pull request by bneedhamia**
Added Eddystone-URL support: added setAdvertisedServiceData() to support BLE Service Data; changed Incomplete to Complete Service UUID list code in Advertising initialization, required by Eddystone-URL protocol; added (for debugging and testing Advertising) getAdvertisingLength() and getAdvertising() to enable a Sketch to view the generated BLE Advertising packet.

This change allows an Arduino 101 to be a beacon, specifically an Eddystone-URL beacon, as used in Google's Physical Web(tm) project.  See https://google.github.io/physical-web/

### CODE REVIEW

**Comment by bneedhamia** [comment]
For an example sketch, see [my Eddystone-URL Arduino 101 Sketch](https://github.com/bneedhamia/CurieEddystoneURL), which Advertises google.com via Eddystone/Physical-Web(tm) protocol .  Should I add a version of this sketch as a CurieBLE example?

**Comment by bneedhamia** [comment]
I noticed I seem to have some typo in keywords.txt, because one of the new functions isn't highlighted in the IDE.  Shall I correct that typo and push it to support-eddystone-url branch on my pull repo?  ...or shall I wait for review to notice it.

**Comment by bigdinotech** [comment]
@bneedhamia sorry for the late review. Yes please go ahead and fix the typo. I will approve the pull request once that is done. Thanks.

**Comment by bneedhamia** [comment]
The keyword.txt corections are in.

**Comment by bigdinotech** [comment]
@calvinatintel please merge

**Comment by bneedhamia** [comment]
@Dan-Emutex @bigdinotech Excellent point.  I'll take a look at @sandeepmistry Eddystone code and BLE library and if appropriate pull in the appropriate interfaces (in a new pull request).  I wasn't aware of Sandeep's Eddystone code.

I had skimmed Sandeep's BLE library before I started, and at least in a quick skim of the code at that time, I didn't see Service Data support in the advertising - obviously from his Eddystone code, it must be hiding in there somewhere.  I'll give his Eddystone code and BLE library a good read-over.  I wouldn't want to diverge from his code.

Thanks again for the catch,
Brad

**Comment by sandeepmistry** [comment]
@bneedhamia service data is currently controlled by calling [```characteristic.broadcast()```](https://github.com/sandeepmistry/arduino-BLEPeripheral/blob/master/BLECharacteristic.h#L48). There is also support to update the advertised value, via the ``setValue`` API if the characteristic is currently broadcasted.

This feature was left out of the CurieBLE library because controlling the advertisement data after ``begin()`` was not supported at the time to my knowledge. Maybe this has changed now?

@Dan-Emutex @bneedhamia thank you for bringing this discussion up. It would be great to continue to keep the CurieBLE API in sync with the BLEPeripheral library.

**Comment by Gerriko** [comment]
Any updates on this topic

**Comment by SidLeung** [comment]
@sandeepmistry , is service data broadcasting needed for the next BLE release?  There was another discussion on similar topic here,

https://github.com/01org/corelibs-arduino101/issues/420

**Comment by sandeepmistry** [comment]
@SidLeung, yes #420 would allow us to accomplish the same thing.

**Comment by ElliotMebane** [comment]
EddystoneURL sample with Curie 2.0.2:
https://github.com/ElliotMebane/Arduino/tree/master/EddystoneURL_Arduino101

**Pull request merged**
