### PR TITLE
Fix Klockwork issues in CurieEEPROM #142

### PR DESCRIPTION
**Pull request by bigdinotech**
-Also fixes issue of not being able to rewrite the last 3/4 of the
EEPROM area

### CODE REVIEW

**Comment by bigdinotech** [comment]
relates to #142 
@SidLeung ready for review
@bbaltz505 are you able to run Klockwork on my PR?

**Comment by bbaltz505** [comment]
KW thinks your PR is fine

**Comment by SidLeung** [comment]
This issue should be eliminated with the changes in 142.

**Comment by SidLeung** [comment]
@calvinatintel Looks good.  Please merge.

**Comment by bbaltz505** [comment]
cherry-picked

**Pull request closed without merging**
