### PR TITLE
Add CurieMailbox library

### PR DESCRIPTION
**Pull request by eriknyquist**
Zephyr sample applications to go with the example sketches
can be found in CODK-M-X86-Samples

### CODE REVIEW

**Comment by eriknyquist** [comment]
@bigdinotech @SidLeung @calvinatintel please review

**Comment by bigdinotech** [comment]
+1 looks good to me but I think this should go into the codk-m branch

**Comment by eriknyquist** [comment]
That's what I thought at first too, but I also think it makes sense to avoid having "CODK-M only" libraries wherever possible. @calvinatintel @SidLeung  what do you think?

**Comment by calvinatintel** [comment]
Well, if it only works on M, I guess it would make sense to put it in M branch https://github.com/01org/corelibs-arduino101/tree/codk-m

**Comment by eriknyquist** [comment]
well you can't say "it only works on M". Right now, CODK-M is the only thing that we provide which makes sense to use with this library. It works just fine in the IDE, and although it would be an odd choice right now, I see no reason to restrict that.

**Comment by eriknyquist** [comment]
As per our discussion last week, I will close this PR and make a new one for the M branch

**Pull request closed without merging**
