### PR TITLE
Updates for Jira-566

### PR DESCRIPTION
**Pull request by jgithubs**
Jira-566, I2S comments to examples

### CODE REVIEW

**Comment by jgithubs** [comment]
@SidLeung Added comments on I2S hookup.

**Comment by eriknyquist** [comment]
looks good to me, @calvinatintel please merge

**Comment by SidLeung** [comment]
Agree.  Looks good.  Ready to merge.

**Comment by eriknyquist** [comment]
@jgithubs hang on, can we get a better message actually? the most important piece of information for future log readers is that this commit is only changing a comment, can we capture that? e.g. "Jira-556: Add informative comments to I2S examples"

**Comment by calvinatintel** [comment]
Comment changed and merged

**Pull request closed without merging**
