### PR TITLE
Fix recipe.ar.pattern to avoid warning at startup

### PR DESCRIPTION
**Pull request by facchinm**
IDE 1.6.6 changed the paths for archive files and complains with a warning if the pattern needs to be rewritten.

### CODE REVIEW

**Comment by calvinatintel** [comment]
@kmsywula @bigdinotech @SidLeung @bbaltz505 Please review

**Comment by SidLeung** [comment]
Brian…

I have not seen “  {archive_file_path}  “  as part of the input parameters to the ARC cross compiler.  The symbol should have been expended into a file by the builder.  An output from mind as follow,

C:\Users\sidneyle\AppData\Roaming\Arduino15\packages\Intel-Test\tools\arc-elf32\1.6.4+1.0/bin/arc-elf32-ar rcs C:\Users\sidneyle\AppData\Local\Temp\build1242165541007227762.tmp/core.a C:\Users\sidneyle\AppData\Local\Temp\build1242165541007227762.tmp\hooks.c.o


Sid

**Comment by bbaltz505** [comment]
@SidLeung On 1.6.6, the parameter does expand to:
'C:\Users\babaltz\AppData\Local\Temp\buildxxxxx.tmp/core.a'
On 1.6.5, it does not.

**Comment by SidLeung** [comment]
The compile log msg I sent you was done with IDE 1.6.4.  So, both 1.6.4 & 1.6.6 can expand the environment symbol correctly.

Sid

**Comment by bbaltz505** [comment]
This post describes the problem I am seeing:
https://github.com/arduino/Arduino/issues/4114

**Comment by SidLeung** [comment]
Brian:

I have not acquired enough knowledge to understand the entire description in the link.  Was it pointing to the platform.txt file is not compatible between IDE versions?

Sid.

**Comment by facchinm** [comment]
The patch is intended for IDE >= 1.6.6 and is not backward compatible (as you noticed). Since the serial monitor timeout issue has been merged in master after 1.6.6, the first release suitable for 101 will be 1.6.7
If you wish to keep backwards compatibility simply drop this patch but a warning will be displayed any time you compile a sketch :smile:

**Comment by bbaltz505** [comment]
Thanks Martino. Given the number of users that may still be on 1.6.5 (and maybe 1.6.4), I suggest we do not merge this patch.

**Comment by calvinatintel** [comment]
Closing the PR since it's not backward compatible

**Comment by calvinatintel** [comment]
Reopening since we're now supporting 1.6.6. We understand that this breaks 1.6.5.

**Comment by calvinatintel** [comment]
cherry-picked

**Pull request closed without merging**
