### PR TITLE
Jira 859. Support BLE descriptor processing.

### PR DESCRIPTION
**Pull request by SidLeung**
Feature added:

For Central mode, added the support for processing
BLE descriptor from a connected Peripheral.  Enable
the user sketch to access to descriptor value,
length info.

Code modifications:

1. peripheral_explorer.ino:
   - Example sketch with added descriptor processing.
2. BLECharacteristic.cpp:
   - Bug fixed in handling multi-descriptors.
3. BLEDescriptor.cpp:
   - For constructors, added initialization of
     descriptor storage and info.
   - For copy constructor and assignment, take into
     the account of descripter value and info.
   - Added API's for readning and returning descriptor
     info, eg. value, size.
4. BLEDescriptor.h:
   - Prototyping.
5. BLEDevice.h:
   - Added descriptor storage declaration.
6. BLECallbacks.cpp:
   - Added call back event for decriptor arrival.
7. BLECallbacks.h:
   - Prototyping.
8. BLECharacteristicImp.cpp:
   - The processing of the descriptor.
9. BLECharacteristicImp.h:
   - Prototyping.
10. BLEServiceImp.cpp:
   - Added descriptor info to constructor.
   - Made copy constructor to be aware of descriptor info.
11. BLEServiceImp.h:
   - Prototyping.

### CODE REVIEW

**Comment by SidLeung** [comment]
@bigdinotech , @eriknyquist , please review the code.

@russmcinnis , @noelpaz , please check out this new feature.  Example sketch included (modified an existing sketch).  Please perform system testing.

**Comment by russmcinnis** [comment]
There is a curly brace missing in peripheral_explorer.ino. I fixed that to test using a 101 with an LED sketch. the descriptor length was 0 so maybe I need to set something on the peripheral or run another device. Anyway we can't go with the pull request since the sketch doesn't compile.

Connecting ...
Connected
Discovering attributes ...
Attributes discovered

Device name: 
Service 1800
Service 1801
Service 19b10000-e8f2-537e-4f6c-d104768a1214
	Characteristic 19b10001-e8f2-537e-4f6c-d104768a1214, properties 0x10
		Descriptor 2901, value 0x

Disconnecting ...
Disconnected

**Comment by russmcinnis** [comment]
Passed system testing for unit testing we need to put a delay(1000) after descriptor.read() in the peripheral_explorer example as Liang noted for this to work so shouldn’t we update the peripheral explorer example to use the delay.
Bat Test Passed

**Comment by SidLeung** [comment]
@russmcinnis , agree and made the change in the sample sketch.  Please check out the change in the sketch.

**Comment by russmcinnis** [comment]
passed system and unit test 
@SidLeung can resolve

**Comment by SidLeung** [comment]
@yashaswini-hanji , please merge this PR and close out the Jira.

**Comment by yashaswini-hanji** [comment]
PR merged and Jira closed

**Pull request merged**
