### PR TITLE
ATLEDGE-384 Remove Esplora specific examples

### PR DESCRIPTION
**Pull request by bigdinotech**
Remove Esplora specific examples

### CODE REVIEW

**Comment by bigdinotech** [comment]
@kmsywula @SidLeung Ready for review

**Comment by kmsywula** [comment]
@calvinatintel, @bigdinotech  code reviewed

**Comment by bigdinotech** [comment]
@calvinatintel I think I made a mistake can you cherry pick the first commit. The 2nd commit still need to be reviewed.

**Comment by bigdinotech** [comment]
Or maybe cherry-pick both if the second one gets reviewed by then

**Comment by bigdinotech** [comment]
@SidLeung @calvinatintel pls review the second commit also

**Comment by SidLeung** [comment]
@calvinatintel Ready for cherrypick.

**Pull request merged**
