### PR TITLE
Improve CurieBLE library

### PR DESCRIPTION
**Pull request by biagiom**
- Improve sketches that use Serial communication
- Update keyword.txt file of CurieBLE library
- Improve the BLEAttribute Class

### CODE REVIEW

**Comment by sandeepmistry** [comment]
We should be careful about adding `while(!Serial) ;` to the example sketches. As this forces people to open the serial monitor when using them. This also means the examples won't run when powering the 101 via a battery or USB wall charger.

The other changes look good to me though.

**Comment by biagiom** [comment]
Hi @sandeepmistry,
thanks for your comments and I think you are right about to be careful when adding `while(!Serial) ;` since people have to open the Serial monitor to execute the next lines of code but I have added it since the sketches use the Serial communication and print some text in `void setup()`, but text could be lost if you don't add the line `while(!Serial) ;`.
I have also noticed that if you leave the Serial monitor open when uploading a new sketch to Arduino/Genuino 101 you can't use the Serial monitor during the upload procedure as well as some seconds after it, but in this way, you avoid the use of `while(!Serial) ;` since if you want to print some text with `Serial.print()` or `Serial.println()`in `void setup()` the text is not lost because when the Serial port is open the Serial monitor is already open. This prevent the loss of data send to the Serial monitor.
If you think that `while(!Serial) ;` is not a really thing to add, so I agree with you and the commits that add `while(!Serial) ;` could be skipped.
I hope to be clear.
Best regards and thank you very much for your contribution about the development of the great CurieBLE library (as well as Node and Bleno).

**Comment by eriknyquist** [comment]
@biagiom please remove the unrelated commit 	b329d08

**Comment by eriknyquist** [comment]
@biagiom please resolve merge conflict. @SidLeung please review.

**Pull request closed without merging**
