### PR TITLE
Sync IPAddress and Wstring with SAM implementation

### PR DESCRIPTION
**Pull request by facchinm**
Test suite failed on these functions

### CODE REVIEW

**Comment by facchinm** [comment]
Depends on #58

**Comment by calvinatintel** [comment]
@SidLeung @kmsywula @intel-larry Please review

**Comment by calvinatintel** [comment]
@facchinm Can you please combine #58 and #59 into one pull request?

**Comment by facchinm** [comment]
@calvinatintel sure, combined into #58, closing this one

**Pull request closed without merging**
