### PR TITLE
pwm improvements

### PR DESCRIPTION
**Pull request by bigdinotech**
-add capability to change pwm signal frequency with analogWriteFrequency
-improve pwm signal frequency accuracy

### CODE REVIEW

**Comment by bigdinotech** [comment]
@eriknyquist @SidLeung ready for review

**Comment by eriknyquist** [comment]
+1

**Comment by eriknyquist** [comment]
@bigdinotech ready for merging?

**Comment by bigdinotech** [comment]
@eriknyquist still needs to be tested

**Pull request closed without merging**
