### PR TITLE
Jira-243 Integrate Flashpack into IDE

### PR DESCRIPTION
**Pull request by calvinatintel**
Do not merge yet

### CODE REVIEW

**Comment by kitsunami** [comment]
@calvinatintel to review.

**Comment by kitsunami** [comment]
Waiting for next FW update.

**Comment by calvinatintel** [comment]
Continued here: https://github.com/01org/corelibs-arduino101/pull/269

**Comment by calvinatintel** [comment]
Moved to a new PR because this one is based on my fork. The new PR is using a branch in this current repo, so that other team members have easier write access.

**Pull request closed without merging**
