### PR TITLE
Update library.properties

### PR DESCRIPTION
**Pull request by SimonePDA**

### CODE REVIEW

**Comment by bbaltz505** [comment]
Hello. Arduino/Genuino 101 support has been merged into the public Adafruit_NeoPixel library but has not been released yet.
adafruit/Adafruit_NeoPixel#92

**Comment by bbaltz505** [comment]
I suggest we close this issue. Changes to NeoPixel should be submitted to Adafruit's official repo.

**Comment by SidLeung** [comment]
@bbaltz505 I am not clear if there was a need to sync our CoreLib with AdaFruit library.  If I, as a user, downloaded the Corelib from the Arduino site and then downloaded the library from AdaFruit, my environment would be some previous version of CoreLib?

**Comment by bbaltz505** [comment]
When I submitted the pull request to the Adafruit repo for Arduino 101 support, I had rebased on the latest. Their latest release is from December which does not include our changes. their next release should include it.
Libraries installed via Library Manager override the one in corelibs.

**Comment by bigdinotech** [comment]
Closing

**Pull request closed without merging**
