### PR TITLE
ATLEDGE-423 Export compiled binary

### PR DESCRIPTION
**Pull request by bigdinotech**
Make changes to platform.txt to allow exporting compiled binary as a
.hex

### CODE REVIEW

**Comment by bigdinotech** [comment]
@kmsywula @SidLeung @bbaltz505 ready for review

**Comment by SidLeung** [comment]
It's interesting to see that the old elf2hex flags was actually creating bin file.  One minor suggestion - a comment above line 78 to indicate that it is creating hex output.

**Comment by bigdinotech** [comment]
@SidLeung I have made the suggested changes.
@calvinatintel ready for cherry-pick

**Comment by SidLeung** [comment]
Thank you, Dino!  It would help newcomers like myself a lot.  @calvinatintel please merge.

**Pull request merged**
