### PR TITLE
Add DMA support to I2S

### PR DESCRIPTION
**Pull request by calvinatintel**
`libarc32drv_arduino101.a` updated. Replaces PR https://github.com/01org/corelibs-arduino101/pull/230.
@bigdinotech @linrjing Please give me a good description of the changes to be put into the git commit.

### CODE REVIEW

**Comment by linrjing** [comment]
@calvinatintel  The description of the git commit can be "I2S DMA implement: supplement library and example". Now the codes have been updated on my feature/i2s_dma branch, please merge it with your branch. The changes are: (1)combine I2SDMA with the existing I2S library；(2)Tx side does not need to add 2 extra buffer;(3)after TX-DMA transfer completed, 4 zero would be pushed into the TX FIFO to make sure all expected data have been transmitted to RX side.

**Comment by linrjing** [comment]
@xieqi @sgbhu @SidLeung  the original request is closed. Calvin helped make a new one here.

**Comment by calvinatintel** [comment]
Added the latest change from linrjing.
@bigdinotech Please test. Once it's confirmed to work, I'll squash the two commits into one.

**Comment by linrjing** [comment]
@calvinatintel @bigdinotech  currently the code is only for the sample resolution = 32 bit.

**Comment by SidLeung** [comment]
@calvinatintel The Flex China team is planning to make the implementation to fix the range the sampling resolutions (24, 16, 8 bits).  I suppose it would be cleaner if we first let this commit emerge to the trunk first, fork a branch, implement the extra supporting resolutions, push, and merge again.  Please advise.

**Comment by calvinatintel** [comment]
@SidLeung Would that break the main repo? If you'd like, I can put it on a branch and you can fork that.

**Comment by calvinatintel** [comment]
About to merge. @bigdinotech Can you confirm?

**Comment by bigdinotech** [comment]
@calvinatintel ready for merge

**Comment by calvinatintel** [comment]
Squashed and merged

**Comment by SidLeung** [comment]
Thanks @calvinatintel and @bigdinotech.  Flex China can now do a fork and add in the new implementation..

**Pull request merged**
