### PR TITLE
Add -std=gnu11 to compiler.c.flags in platform.txt

### PR DESCRIPTION
**Pull request by eriknyquist**
Related to issue #221

### CODE REVIEW

**Comment by eriknyquist** [comment]
@calvinatintel do not merge. I need to run compile tests first.

**Comment by calvinatintel** [comment]
Not doing something is my default position

**Comment by eriknyquist** [comment]
Compile tests passed for Windows, OSX & Linux64. Linux32 failed for unrelated reasons.

**Comment by eriknyquist** [comment]
@bigdinotech @SidLeung ready for review

**Comment by bigdinotech** [comment]
@calvinatintel looks good to me

**Pull request merged**
