### PR TITLE
Jira509: modify the example of motion, zero-motion and freefall

### PR DESCRIPTION
**Pull request by linrjing**
@xieqi @sgbhu @SidLeung 
Jira509:add 'while (! serial);' and change the copyright to 2016; fix indicator light behavior for IMU example ZeroMotionDetect.

### CODE REVIEW

**Comment by SidLeung** [comment]
@bigdinotech @calvinatintel Dino:  Did you make the proposed change and have Calvin to merge it into the trunk for Bellatrix release?

**Comment by linrjing** [comment]
@xieqi @sgbhu @SidLeung Jira509:Remove Tap Shock and Tap Quiet from Library

**Comment by kitsunami** [comment]
Please clean up the commit so that it is just one, with a description of the changes you are making.

**Comment by linrjing** [comment]
@kitsunami @SidLeung There is only one commit now. The changes:(1) fix the indicator light behavior for IMU example ZeroMotionDetect; (2) remove Tap Shock and Tap Quite from library, (3) change setZeroMotionDetectionThreshold(value) to setZeroMotionDetectionDuration(value) at line 794 in file CurieIMU.cpp.

**Comment by bigdinotech** [comment]
@calvinatintel @SidLeung +1

**Comment by calvinatintel** [comment]
cherry-picked

**Pull request closed without merging**
