### PR TITLE
Updating compile command and driver lib for new toolchain

### PR DESCRIPTION
**Pull request by bbaltz505**

### CODE REVIEW

**Comment by bbaltz505** [comment]
@SidLeung please review. This PR passes BAT testing and compile tests

**Comment by SidLeung** [comment]
@bbaltz505 @calvinatintel   Looks good.  Please merge.  I didn't know the -lnsim flag is in application compile flag.  I thought it was used for building the toolchain.

**Comment by bbaltz505** [comment]
@SidLeung have you confirmed that this toolchain (http://mkj.ndg.intel.com/view/ARC%20Toolchain/job/ARC_Toolchain-Linux64-Sid/ws/arc-toolchain-linux64-arcem.tar.bz2) fixes the original floating point issue?

**Comment by SidLeung** [comment]
I am going to verify that today.  Will keep you update.

**Comment by SidLeung** [comment]
The performance of the new toolchain is not good at all.  Need to ping on the Synopsis team ASAP.

**Comment by SidLeung** [comment]
@bbaltz505 @calvinatintel Looks good.  Please merge.

**Pull request merged**
