### PR TITLE
JIRA-640 I2C timout

### PR DESCRIPTION
**Pull request by xieqi**
Using PaulStoffregen's test sketch, attached here, please change the .txt to .ino for test.  I tested with Aardvark, the time for 100KHz is about 1480 after this patch.
[i2c_timeout.txt](https://github.com/01org/corelibs-arduino101/files/370992/i2c_timeout.txt)

### CODE REVIEW

**Comment by xieqi** [comment]
@SidLeung @linrjing @sgbhu

**Comment by bigdinotech** [comment]
+1

**Comment by calvinatintel** [comment]
@eriknyquist syntaxbot to rescue?

**Comment by eriknyquist** [comment]
Looks fine to me

**Comment by calvinatintel** [comment]
cherry-picked

**Comment by bigdinotech** [comment]
@calvinatintel can you generate a .a file

**Pull request closed without merging**
