### PR TITLE
CurieBLE: Add support for "some" 16-bit + 128-bit UUID's and shortened name

### LINKED ISSUE #371: CurieBLE: cannot discover advertised 16-bit service of SensorTag
When using the scan example with the my TI SensorTag I'm not able to see the `aa80` service it advertises which is in the advertisement data it advertises. However, using LightBlue on iOS I can see the 0xaa80 service.

### PR DESCRIPTION
**Pull request by sandeepmistry**
These changes resolve #371 and #372 for me.

### CODE REVIEW

**Comment by SidLeung** [comment]
This issue is logged as Jira 792.  It is under internal review, testing.  Upon completion, will be merged to master and in the nightly JSON build.  Will update here when the JSON has this change.

**Comment by sandeepmistry** [comment]
The data structure for "some" and "all" EIR types are the same, it's more semantics. "All" means all the services the peripheral provides are advertised,  "some" means only some of the services are advertised, when the connected to the peripheral can have more services than advertised.

**Comment by SidLeung** [comment]
PR #450 addresses this request.  Will be in the next release.

**Comment by sandeepmistry** [comment]
Closing this, as this PR was replicated in #450 which has been merged.

**Pull request closed without merging**
