### PR TITLE
Klocwork issues

### PR DESCRIPTION
**Pull request by kevin306**
All relevant Klocwork fixes.

### CODE REVIEW

**Comment by pricopb** [comment]
@calvinatintel, @bbaltz505 please hold off the merge. 
I've just run some tests ans it looks like I introduce some new issues while fixing Klocwork#137.
Please let me do a bit more digging and I'll come back with a resolution.

**Comment by bbaltz505** [comment]
Ok. Thanks Bogdan.

**Comment by kevin306** [comment]
@bbaltz505 @calvinatintel I have updated pull request with Bogdans fix for Klocwork#137.

**Comment by pricopb** [comment]
Calvin, Brian, I would say we are good to review the changes before merge.
Thanks very much!

**Comment by bbaltz505** [comment]
Thanks Bogdan and Dan. @kmsywula can you review these KW fixes?

**Comment by bbaltz505** [comment]
@SidLeung  @bigdinotech please review. These are minor fixes for Klocwork defects. Klocwork scans showed possible memory leaks and other issues.

**Comment by bigdinotech** [comment]
@calvinatintel code looks good tom me +1

**Comment by calvinatintel** [comment]
@kmsywula @SidLeung Please review

**Comment by bbaltz505** [comment]
There are 2 KW defects still in this PR so @pricopb will probably push another update.

**Comment by pricopb** [comment]
I think we are good now @bbaltz505!
Could you, please, review and merge?
Thank you abd sorry for the delay. :-(

**Comment by calvinatintel** [comment]
@SidLeung @kmsywula @bigdinotech Please review again!

**Comment by bbaltz505** [comment]
Klocwork likes your latest changes. :-)  +1 from me.

**Comment by calvinatintel** [comment]
@bbaltz505 Since this issue was for resolving Klocwork messages, I think it should be merged in. Thoughts?

**Comment by bbaltz505** [comment]
I agree

**Pull request merged**
