### PR TITLE
Jira-462: Call Available() after calling end() indicated data available.

### PR DESCRIPTION
**Pull request by SidLeung**
Code Modifications:

1.  Added checking of device open in these routines: available, read, peek.
    Will return 0 or -1 if device is not opened to indicate invalid operation.

### CODE REVIEW

**Comment by SidLeung** [comment]
@bigdinotech @kmsywula Please review the changes to fix Jira-462, Serial.end() and Serial.available() issue.

**Comment by bbaltz505** [comment]
No new KW issues in this PR

**Comment by bigdinotech** [comment]
@calvinatintel looks good. Please merge.

**Comment by calvinatintel** [comment]
Cherry-picked

**Pull request closed without merging**
