### PR TITLE
Fixing sketch size calculation (text + ctors + rodata + datas

### PR DESCRIPTION
**Pull request by bbaltz505**
Reopening closed PR #126 to fix sketch size.

### CODE REVIEW

**Comment by bbaltz505** [comment]
@pricopb @SidLeung

**Comment by bbaltz505** [comment]
```
...\Blink.ino.elf  :
section     size         addr
text       13600   1073954816 <-- 
ctors         12   1073968416 <-- 
rodata       440   1073968428 <-- 
datas       3156   2818629632 <--
bss         1916   2818632788
heap        8192   2818634704
stack       2560   2818642896
.comment     118            0
Total      29994
```
The IDE then reports:
```
Sketch uses 17,208 bytes (8%) of program storage space. Maximum is 196,608 bytes.
```

**Comment by SidLeung** [comment]
@bbaltz505 We only have 152 KB of Flash storage for the current setup.  Can change that in future releases.

**Comment by bbaltz505** [comment]
Ok. i can update boards.txt. What is the exact # of bytes? 155,648?

**Comment by SidLeung** [comment]
Yes, it's 155,648 bytes.

**Comment by bbaltz505** [comment]
@SidLeung Corrected the max sketch size.

**Comment by SidLeung** [comment]
@calvinatintel Looks good.  Ready to merge.  Thank you, Brian.

**Pull request merged**
