### PR TITLE
CurieBLE: Correct | to &, and swap order of write vs write without response

### PR DESCRIPTION
**Pull request by sandeepmistry**
Fixes https://github.com/01org/corelibs-arduino101/issues/385.

### CODE REVIEW

**Comment by SidLeung** [comment]
Tracked by Jira 889.

**Comment by SidLeung** [comment]
@sandeepmistry , I suppose you used the Raspberry Pi to test this bug fix as you stated here,

https://github.com/01org/corelibs-arduino101/issues/385#issuecomment-281695927

**Comment by sandeepmistry** [comment]
@SidLeung yes, both macOS and a Raspberry Pi.

**Comment by SidLeung** [comment]
@sandeepmistry , thank you.

**Comment by russmcinnis** [comment]
system test passed with PR490 that includes this.

**Pull request merged**
