### PR TITLE
Issue #241: make Serial1 release GPIO pins on end()

### PR DESCRIPTION
**Pull request by eriknyquist**
UARTClass::init() muxes out the UART pins to Arduino header pins 0/1.
Reset the mux on UARTClass::end() so that pins 0/1 can be used as GPIOs
again.

### CODE REVIEW

**Comment by eriknyquist** [comment]
@bigdinotech @calvinatintel @SidLeung ready for review. This fixes issue #241.

**Comment by bigdinotech** [comment]
@calvinatintel @eriknyquist +1 looks good to me

**Comment by eriknyquist** [comment]
@calvinatintel don't merge yet, I want some independent testing first

**Comment by celskeggs** [comment]
@eriknyquist In case it helps, I've tested this and confirmed that it fixes the problem that I reported in #241.

**Comment by eriknyquist** [comment]
Thanks @celskeggs.
@calvinatintel Janet has verified. This can be merged now.

**Pull request merged**
