### PR TITLE
Jira 797, Central can scan with MAC address, git 376

### PR DESCRIPTION
**Pull request by SidLeung**
New feature:
-  Add the capability for a Central to scan for a
   Peripheral using its MAC address.

Code Modifications:
-  Added the API for MAC address scanning.
-  For Device Manager, added provision for holding the
   MAC address of a Peripheral.
-  For scan discovery handler, added the checking
   for MAC address comparison, if MAC address scanning
   is requested.

File changes:

1. libraries/CurieBLE/src/BLEDevice.cpp:
   - Added API for MAC address scanning.
2. libraries/CurieBLE/src/BLEDevice.h:
   - API definition.
3. libraries/CurieBLE/src/internal/BLEDeviceManager.cpp:
   - Added provision for storing the MAC address.
   - Added MAC address comparison in the scan discovery
     handle if MAC address scanning is selected.
4. libraries/CurieBLE/src/internal/BLEDeviceManager.h:
   - Prototyping.

### CODE REVIEW

**Comment by SidLeung** [comment]
@bigdinotech @eriknyquist , please review the code change.  @noelpaz @russmcinnis , please note that this PR is originated from PR #397.  If you have tested it against Jira #797, please wait for code approval to perform final verification prior to merging.

**Comment by SidLeung** [comment]
@noelpaz @russmcinnis , please confirm if this PR passed verification testing.

**Comment by SidLeung** [comment]
@noelpaz , @russmcinnis , please provide feedback to close out this PR.

**Comment by noelpaz** [comment]
It passed verification testing

**Comment by SidLeung** [comment]
@yashaswini-hanji @calvinatintel , would you please merge this PR to the main trunk.  It has gone through code approval and testing.

**Comment by yashaswini-hanji** [comment]
Changes merged to base branch.

**Pull request closed without merging**
