### PR TITLE
Add Paul Stoffregen's SerialFlash library

### PR DESCRIPTION
**Pull request by eriknyquist**

### CODE REVIEW

**Comment by eriknyquist** [comment]
@calvinatintel, testing is underway, being done by @bigdinotech. He will notify you for merging once he is satisfied with testing.

**Comment by bigdinotech** [comment]
@eriknyquist maybe we should remove the MP3Player example since we are shipping with it and that specific sketch does not compile and is designed to work with Teensy.

**Comment by eriknyquist** [comment]
@bigdinotech good call, I will remove it and replace with an example for reading/writing files since no such examples are in there yet

**Comment by eriknyquist** [comment]
@bigdinotech updated the same commit, removed MP3Player example and added FileWrite example.

**Comment by bigdinotech** [comment]
@calvinatintel looks good. I tested the sketches yesterday. Please merge

**Comment by eriknyquist** [comment]
@bigdinotech FYI that FileWrite sketch is new content, i.e. I just wrote it right now. It worked for me, but maybe you should test it yourself quickly before merging.

**Comment by bigdinotech** [comment]
@calvinatintel tested the new example sketch also. Please merge

**Pull request merged**
