### PR TITLE
Add error message if using IDE 1.6.6

### PR DESCRIPTION
**Pull request by calvinatintel**
@bigdinotech @kmsywula @intel-larry @SidLeung Please review

### CODE REVIEW

**Comment by bigdinotech** [comment]
@calvinatintel looks fine to me. assuming that they use that number for 1.6.7
Have we tested on the nightly build?

**Comment by intel-larry** [comment]
We need to test it.

**Comment by calvinatintel** [comment]
Successfully blocks 1.6.4, 1.6.5, 1.6.6.
Compiles correctly on the latest nightly.

**Comment by bigdinotech** [comment]
I printed the value of ARDUINO in nightly 1.6.7 and it showed 10607

**Pull request merged**
