### PR TITLE
Rethink SerialFlash class

### PR DESCRIPTION
**Pull request by facchinm**
Removing the fork of SerialFlash library allows the freedom to track mainline without any maintenance burden. 
Since the library in no longer included, all examples have been patched to add a direct link to library manager.

_Do not merge yet_ : https://github.com/PaulStoffregen/SerialFlash/pull/35 needs to be merged and published before this patch applies correctly

### CODE REVIEW

**Comment by eriknyquist** [comment]
Looks good @facchinm, I'll watch the PR on Paul's library and merge this one after it.
Just one suggestion, if there are only 2 differences (the overloaded `begin` and the CS pin) between these examples and Paul's examples, then I think it's better just to add those lines as comments in Paul's examples with a "use this line for Arduino/Genuino 101" message. Might as well avoid duplicating the example code too if we can!

**Comment by facchinm** [comment]
I don't think it is a good idea to remove completely the examples, the OOTB experience could suffer (I agree that they are unnecessary since avoiding the overloaded constructor approach makes this library a pure wrapper). I commented on Paul's PR about tested compatibility so I'm confident it will be merged soon

**Comment by sandeepmistry** [comment]
It would be awesome if we could change `SerialFlash.begin(SPI1, FlashChipSelect);` in the examples to something like `CurieSerialFlash.begin()` later on.

**Comment by eriknyquist** [comment]
@sandeepmistry then, in order to convert a sketch from using default SPI to using 101 built in SPI-flash, you have to search/replace all occurrences of 'SerialFlash'. This way, you only have to change the `begin()` call.

**Comment by sandeepmistry** [comment]
@eriknyquist good point regarding re-using existing sketches.

I'm still not too keen on making the user's have to remember that pin `21` is the CS pin, what do you think about add a constant in the core for it? One possible name is `SPI_FLASH_CS`, similar could be done for the SPI port.

**Comment by eriknyquist** [comment]
Any progress here? can we nudge this one along https://github.com/PaulStoffregen/SerialFlash/pull/35 ?

**Comment by facchinm** [comment]
Merged in mainline, please proceed with this one (I'll push a rebase immadiately :smile: )

**Comment by eriknyquist** [comment]
Thanks @facchinm. Any idea when the next SerialFlash release will be available in the IDE library manager? Or maybe @PaulStoffregen is the one to ask?

**Comment by eriknyquist** [comment]
Also, @facchinm, I think it makes sense for this to be a single commit. Could you squash please?

**Comment by facchinm** [comment]
@eriknyquist three commits make more sense to me but if you prefer squashing it should be a matter of a tick in github's UI during merge :smile:

**Comment by PaulStoffregen** [comment]
> Or maybe @PaulStoffregen is the one to ask?

I have other issues still pending on SerialFlash, mainly support for newer chips and some usability improvements with the examples.  Just yesterday OSH Park delivered a new board I need for testing the largest Micron chips.  Planning to solder it tomorrow and add support for these chips.

If you *really* need a release to push to the boards manager asap, I could do one.  But in just a matter of days I'll be making another release for these new chips.  Would prefer to do just 1 new release.

**Comment by eriknyquist** [comment]
@facchinm fine, as long as each commit makes sense /compiles on its own. @PaulStoffregen also fine, not necessarily in a rush, just wanted the ETA. a few days from now is fine.

**Comment by kitsunami** [comment]
@PaulStoffregen any update on this? Can you review and merge the pull request from @facchinm ?

**Comment by eriknyquist** [comment]
@kitsunami my mistake, Paul has merged this. It was a new release of SerialFlash we were waiting for, so that 101 users can just grab SerialFlash from the Library Manager.

@PaulStoffregen just a friendly ping, do you have any plans for an upcoming release of your SerialFlash library?

**Comment by PaulStoffregen** [comment]
Since November, all my dev cycles have been going into a USB Host library... which has turned out to be the most challenging code I've ever written.  SerialFlash and many others have taken a back seat lately.  I actually have a small pile of new chips to test with SerialFlash.  Hope to get back to this and so much more in another few weeks.

**Comment by eriknyquist** [comment]
Understood @PaulStoffregen, appreciate the update! good luck with the USB host lib :)

**Comment by sandeepmistry** [comment]
@PaulStoffrege another friendly ping, would you be able to tag a new release of your SerialFlash library?

**Comment by PaulStoffregen** [comment]
@sandeepmistry - Done

**Comment by PaulStoffregen** [comment]
Perhaps a bit off-topic... do any of your Intel guys have a contact with Winbond who could get me samples of their new W25M02GVZE chip, for testing with SerialFlash?

**Comment by SidLeung** [comment]
@kitsunami You may have a contact with Winbond?

**Comment by sandeepmistry** [comment]
@PaulStoffregen many thanks!

**Comment by PaulStoffregen** [comment]
Oh, looks like Arrow actually has some in stock.  I just ordered a few.

**Pull request merged**
