### PR TITLE
add support for Power Management library

### PR DESCRIPTION
**Pull request by bigdinotech**

### CODE REVIEW

**Comment by bigdinotech** [comment]
@eriknyquist @SidLeung Ready for review

**Comment by bigdinotech** [comment]
Correct

**Comment by eriknyquist** [comment]
Hold on the merge. I'ma ask Russ to run the BAT tests since we're changing the .a file. Should be able to merge in the next hour.

**Comment by bigdinotech** [comment]
too late already pulled the trigger lol

**Comment by eriknyquist** [comment]
that's OK, we'll run them anyway

**Comment by eriknyquist** [comment]
Passed. Closing.

**Comment by solidcloudio** [comment]
how does this work?  I saw the related lib https://github.com/bigdinotech/Arduino101Power but dont see Power.h in this PowerManagement Changeset.  Any examples of using the PowerManagement library?

**Comment by bigdinotech** [comment]
@solidcloudio if you download and install the library at https://github.com/bigdinotech/Arduino101Power It has some examples built in

**Comment by solidcloudio** [comment]
What version of the corelibs and tools are require to run the examples under https://github.com/bigdinotech/Arduino101Power?  The latest 1.8.2 doesnt work with Arduino 101 boards, so I'm running 1.8.1.  If I update to the tips of both corelibs and tools, I can't compile for Arduino 101.

Seems there were breaking changes in 1.8.2 in the BLE library as well..

**Comment by bigdinotech** [comment]
@solidcloudio what kind of compile issues are you seeing?
We are not far from a release of the next version of corelibs/tools. We already tagged  the tip of corelibs.
Are you able to wait for that? That would make the updating to the latest corelibs/tools easier.

**Comment by solidcloudio** [comment]
This is what I'm seeing.  All working fine with 1.8.1 and Intel Curie boards 1.7.  If I then want to use the PowerLibrary - https://github.com/bigdinotech/Arduino101Power I download this library.  looking at the examples the have:

`
#include <Power.h>
#include "CurieIMU.h"`

So, I assume that the src folder contents go with the existing tools under: 
`~/.arduino15/packages/Intel/hardware/arc32/1.0.7/cores/arduino`

So I run:
`cp -r * ~/.arduino15/packages/Intel/hardware/arc32/1.0.7/cores/arduino`

This copies Power.h, etc..  to the core folder.   Now if I try to compile WakeFromIMU.,ino (example)  I get:

> fatal error: dccm/dccm_alloc.h No such file or directory #include "dccm/dccm_alloc.h"

It's correct, dccm is missing from ~/.arduino15/packages/Intel/hardware/arc32/1.0.7/cores/arduino

This is where the core_libs update is now required.,  https://github.com/01org/corelibs-arduino101/tree/master/cores/arduino/dccm  - DCCM is not present in 1.8.1 and 1.0.7 Intel Curie Tools.

So, if I update the corelibs now..  deleting and copying https://github.com/01org/corelibs-arduino101 to 
~/.arduino15/packages/Intel/hardware/arc32/1.0.7/

Now when I compile I get the error about Power.h missing.  Copying this back in..  Now compiling I get:

> /fork/exec /home/ubuntu/.arduino15/packages/Intel/tools/arduino101load: permission denied   Error compiling for board Arduino/Genduino 101.

So, I'll copy down the latest tools..  updating the folder: ~/.arduino15/packages/Intel/tools/arduino101load/1.6.9+1.28

I get the same error as above  permission denied...  plus a new error complaining about: 
In the file included from 

> /home/ubuntu/.arduino15/packages/Intel/hardware/arc32/1.0.7/cores/arduino/Power.h 58:0 from /home/ubuntu/Downloads/Arduino101-Power-master/examples/wakefromIMU.ino:1
/home/ubuntu/.arduino15/packages/Intel/hardware/arc32/1.0.7/cores/arduino/wsrc.h 29:29 warning backslash and newline seperated by space [enabled by default] stat &= ~GPIO_MODE_MASK:\

> /fork/exec /home/ubuntu/.arduino15/packages/Intel/tools/arduino101load: permission denied   Error compiling for board Arduino/Genduino 101.

**Comment by bigdinotech** [comment]
@solidcloudio try installing the latest version of the core-libs 2.02 should be out now

**Comment by solidcloudio** [comment]
ok, i'll try it out

**Pull request closed without merging**
