### PR TITLE
Rename CurieBle to CurieBLE

### PR DESCRIPTION
**Pull request by sandeepmistry**
Similar to #90, it's more Arduino style to leave acronyms uppercase. So, these changes rename ```CurieBle``` to ```CurieBLE```.

Once again we'll have to sync the tutorial content prior to releasing.
 * https://www.arduino.cc/en/Tutorial/Genuino101CurieBLEHeartRateMonitor

### CODE REVIEW

**Comment by sandeepmistry** [comment]
I've rebased this and removed the previous merge conflict.

**Comment by soundanalogous** [comment]
Isn't this going to break any existing users' sketches that import `CurieBle.h`?

**Comment by sandeepmistry** [comment]
@soundanalogous yes, it is a breaking change. It was discussed internally at Arduino, leaving acronyms all uppercase is more Arduino "style".

**Comment by calvinatintel** [comment]
@SidLeung @bigdinotech Please review

**Comment by bigdinotech** [comment]
@calvinatintel please merge

**Comment by calvinatintel** [comment]
Cherry-picked

**Pull request closed without merging**
