### PR TITLE
Test commit. Do not merge.

### PR DESCRIPTION
**Pull request by eriknyquist**
Add a poorly-formatted bogus source file to test the automated formatting.

### CODE REVIEW

**Comment by ndgbuilder** [comment]
I've detected that your changes do not match our desired coding style.

Please download the following patch: https://gist.github.com/eriknyquist/b069ad92f3905131d5e7c45379c9ceb6/raw
Then, update your Pull Request with the following commands
(Where <clone> is your locally cloned fork, and <branch> is the branch on which your changes live):
    cd <clone>
    git checkout <branch>
    patch -p1 < corelibs-arduino101-pr-223.patch
    git commit -a --amend --no-edit
    git push origin <branch> --force

**This is an auto-generated message**

**Comment by ndgbuilder** [comment]
I've detected that your changes do not match our desired coding style.

Please download the following patch: https://gist.github.com/eriknyquist/c4ee1f257906b84d4e61be3fef38a5e5/raw
Then, update your Pull Request with the following commands
(Where <clone> is your locally cloned fork, and <branch> is the branch on which your changes live):
    cd <clone>
    git checkout <branch>
    patch -p1 < corelibs-arduino101-pr-223.patch
    git commit -a --amend --no-edit
    git push origin <branch> --force

**This is an auto-generated message**

**Comment by ndgbuilder** [comment]
I've detected that your changes do not match our desired coding style.

Please download the following patch: https://gist.github.com/eriknyquist/bcb6e45167de545bc29a683bc564dee7/raw
Then, update your Pull Request with the following commands
(Where <clone> is your locally cloned fork, and <branch> is the branch 
on which your changes live):

    cd <clone>
    git checkout <branch>
    patch -p1 < corelibs-arduino101-pr-223.patch
    git commit -a --amend --no-edit
    git push origin <branch> --force

**This is an auto-generated message**

**Comment by ndgbuilder** [comment]
I've detected that your changes do not match our desired coding style.

Please download the following patch: https://gist.github.com/eriknyquist/f312b8a0625008eb077b629d12a1cf85/raw
Then, update your Pull Request with the following commands
(Where \<clone\> is your locally cloned fork, and \<branch\> is the branch 
on which your changes live):

    cd <clone>
    git checkout <branch>
    patch -p1 < corelibs-arduino101-pr-223.patch
    git commit -a --amend --no-edit
    git push origin <branch> --force

**This is an auto-generated message**

**Comment by calvinatintel** [comment]
Message needs to say how to download the patch.
Does the system tell you the branch name? It'd be awesome if that can be embedded into the message.

**Comment by ndgbuilder** [comment]
I've detected that your changes do not match our desired coding style.

Please download the following patch: https://gist.github.com/eriknyquist/8ca9a1c1857171412474b4909ecb49b8/raw
Then, update your Pull Request with the following commands
(Where \<clone\> is your locally cloned fork, and \<branch\> is the branch 
on which your changes live):

    cd <clone>
    git checkout <branch>
    patch -p1 < corelibs-arduino101-pr-223.patch
    git commit -a --amend --no-edit
    git push origin <branch> --force

If you want to avoid getting this message in future, please see this
wiki page (TODO: create wiki page) for instructions on how to set up a
pre-commit hook that will automatically format your code before you push.

**This is an auto-generated message**

**Comment by ndgbuilder** [comment]
I've detected that your changes do not match our desired coding style.

Please download the following patch: https://gist.github.com/eriknyquist/a19c9171210e7520c1c2ab539136b093/raw
Then, update your Pull Request with the following commands
(Where \<clone\> is your locally cloned fork, and \<branch\> is the branch 
on which your changes live):

    cd <clone>
    git checkout <branch>
    curl https://gist.github.com/eriknyquist/a19c9171210e7520c1c2ab539136b093/raw > corelibs-arduino101-pr-223.patch
    patch -p1 < corelibs-arduino101-pr-223.patch
    git commit -a --amend --no-edit
    git push origin <branch> --force

If you want to avoid getting this message in future, please see this
wiki page (TODO: create wiki page) for instructions on how to set up a
pre-commit hook that will automatically format your code before you push.

**This is an auto-generated message**

**Comment by calvinatintel** [comment]
`curl URL -o corelibs-arduino101-pr-223.patch`

**Comment by ndgbuilder** [comment]
I've detected that your changes do not match our desired coding style.

Please download the following patch: https://gist.github.com/ndgbuilder/87fd38c13356b589341cfeaf44e788e9/raw
Then, update your Pull Request with the following commands
(Where \<clone\> is your locally cloned fork)

    cd <clone>
    git checkout 
    curl https://gist.github.com/ndgbuilder/87fd38c13356b589341cfeaf44e788e9/raw > corelibs-arduino101-pr-223.patch
    patch -p1 < corelibs-arduino101-pr-223.patch
    git commit -a --amend --no-edit
    git push origin  --force
on which your changes live):

If you want to avoid getting this message in future, please see this
wiki page (TODO: create wiki page) for instructions on how to set up a
pre-commit hook that will automatically format your code before you push.

**This is an auto-generated message**

**Comment by ndgbuilder** [comment]
I've detected that your changes do not match our desired coding style.

Please download the following patch: https://gist.github.com/ndgbuilder/2e0b8451fb35ea5ce1f53228e3178b42/raw
Then, update your Pull Request with the following commands
(Where \<clone\> is your locally cloned fork)

    cd <clone>
    git checkout 
    curl https://gist.github.com/ndgbuilder/2e0b8451fb35ea5ce1f53228e3178b42/raw > corelibs-arduino101-pr-223.patch
    patch -p1 < corelibs-arduino101-pr-223.patch
    git commit -a --amend --no-edit
    git push origin  --force
on which your changes live):

If you want to avoid getting this message in future, please see this
wiki page (TODO: create wiki page) for instructions on how to set up a
pre-commit hook that will automatically format your code before you push.

**This is an auto-generated message**

**Comment by ndgbuilder** [comment]
I've detected that your changes do not match our desired coding style.

Please download the following patch: https://gist.github.com/ndgbuilder/eb42800875e4b93dd9306090abb7ff2c/raw
Then, update your Pull Request with the following commands
(Where \<clone\> is your locally cloned fork)

    cd <clone>
    git checkout test1
    curl https://gist.github.com/ndgbuilder/eb42800875e4b93dd9306090abb7ff2c/raw > corelibs-arduino101-pr-223.patch
    patch -p1 < corelibs-arduino101-pr-223.patch
    git commit -a --amend --no-edit
    git push origin test1 --force
on which your changes live):

If you want to avoid getting this message in future, please see this
wiki page (TODO: create wiki page) for instructions on how to set up a
pre-commit hook that will automatically format your code before you push.

**This is an auto-generated message**

**Comment by ndgbuilder** [comment]
I've detected that your changes do not match our desired coding style.

Please download the following patch: https://gist.github.com/ndgbuilder/1c2e12a8ac86c8fb06ac8699770a5d25/raw
Then, update your Pull Request with the following commands
(Where \<clone\> is your locally cloned fork)

    cd <clone>
    git checkout test1
    curl https://gist.github.com/ndgbuilder/1c2e12a8ac86c8fb06ac8699770a5d25/raw > corelibs-arduino101-pr-223.patch
    patch -p1 < corelibs-arduino101-pr-223.patch
    git commit -a --amend --no-edit
    git push origin test1 --force

If you want to avoid getting this message in future, please see this
wiki page (TODO: create wiki page) for instructions on how to set up a
pre-commit hook that will automatically format your code before you push.

**This is an auto-generated message**

**Comment by ndgbuilder** [comment]
I've detected that your changes do not match our desired coding style.

I created a patch to fix this, which you can easily download
and apply to your Pull Request using the following commands
(Where \<clone\> is your locally cloned fork)

    cd <clone>
    git checkout test1
    curl https://gist.github.com/ndgbuilder/5ca1429a0f1fe008ed38a549aae6853c/raw > corelibs-arduino101-pr-223.patch
    patch -p1 < corelibs-arduino101-pr-223.patch
    git commit -a --amend --no-edit
    git push origin test1 --force

If you want to avoid getting this message in future, please see this
wiki page (TODO: create wiki page) for instructions on how to set up a
pre-commit hook that will automatically format your code before you push.

**This is an auto-generated message**

**Comment by ndgbuilder** [comment]
I've detected that your changes do not match our desired coding style.

I created a patch to fix this, which you can easily download and apply to your
Pull Request using the following commands (Where \<clone\> is your locally 
cloned fork):

    cd <clone>
    git checkout test1
    curl https://gist.github.com/ndgbuilder/df491570fb5eb1807246a40d7c5db373/raw > corelibs-arduino101-pr-223.patch
    patch -p1 < corelibs-arduino101-pr-223.patch
    git commit -a --amend --no-edit
    git push origin test1 --force

If you want to avoid getting this message in future, please see this wiki page
(TODO: create wiki page) for instructions on how to set up a pre-commit hook
that will automatically format your code before you push.

**This is an auto-generated message**

**Comment by ndgbuilder** [comment]
I've detected that your changes do not match our desired coding style.

I created a patch to fix this, which you can easily download and apply to your
Pull Request using the following commands (Where \<clone\> is your locally 
cloned fork):

    cd <clone>
    git checkout test1
    curl https://gist.github.com/ndgbuilder/0abbd9ca12ca9d5620db02ace1b608d6/raw > corelibs-arduino101-pr-223.patch
    patch -p1 < corelibs-arduino101-pr-223.patch
    git commit -a --amend --no-edit
    git push origin test1 --force

If you want to avoid getting this message in future, please see this wiki page
(TODO: create wiki page) for instructions on how to set up a pre-commit hook
that will automatically format your code before you push.

**This is an auto-generated message**

**Comment by ndgbuilder** [comment]
I've detected that your changes do not match our desired coding style.

I created a patch to fix this, which you can easily download and apply to your
Pull Request using the following commands (Where \<clone\> is your locally 
cloned fork):

    cd <clone>
    git checkout test1
    curl https://gist.github.com/ndgbuilder/9d27e769694fef5957a09d3e587af9c1/raw -o corelibs-arduino101-pr-223.patch
    patch -p1 < corelibs-arduino101-pr-223.patch
    git commit -a --amend --no-edit
    git push origin test1 --force

If you want to avoid getting this message in future, please see
[this wiki page](Creating-a-pre-commit-hook-for-clang-format)
for instructions on how to set up a pre-commit hook
that will automatically format your code before you push.

**This is an auto-generated message**

**Comment by ndgbuilder** [comment]
I've detected that your changes do not match our desired coding style.

I created a patch to fix this, which you can easily download and apply to your
Pull Request using the following commands (Where \<clone\> is your locally 
cloned fork):

    cd <clone>
    git checkout test1
    curl https://gist.github.com/ndgbuilder/9fe8a38505b332a6fb49d7df881e6c56/raw -o corelibs-arduino101-pr-223.patch
    patch -p1 < corelibs-arduino101-pr-223.patch
    git commit -a --amend --no-edit
    git push origin test1 --force

If you want to avoid getting this message in future, please see
[[this wiki page|Creating-a-pre-commit-hook-for-clang-format]]
for instructions on how to set up a pre-commit hook
that will automatically format your code before you push.

**This is an auto-generated message**

**Comment by ndgbuilder** [comment]
I've detected that your changes do not match our desired coding style.

I created a patch to fix this, which you can easily download and apply to your
Pull Request using the following commands (Where \<clone\> is your locally 
cloned fork):

    cd <clone>
    git checkout test1
    curl https://gist.github.com/ndgbuilder/221c2d081422ac4f020fd6243eb8b76d/raw -o corelibs-arduino101-pr-223.patch
    patch -p1 < corelibs-arduino101-pr-223.patch
    git commit -a --amend --no-edit
    git push origin test1 --force

If you want to avoid getting this message in future, please see [this wiki page](https://github.com/01org/corelibs-arduino101/wiki/Creating-a-pre-commit-hook-for-clang-format)
for instructions on how to set up a pre-commit hook that will automatically
format your code before you push.

**This is an auto-generated message**

**Pull request closed without merging**
