### PR TITLE
check mux mode when using digitalWrite

### PR DESCRIPTION
**Pull request by bigdinotech**
-check and make sure that the pin is in GPIO_MUX_MODE when doing a
digitalWrite()
-this has a slight performance impact of digitalWrite
-it also comsumes an extra byte in SRAM per pin
-it does however give us the ability to track the muxing state of each
pin

### CODE REVIEW

**Comment by bigdinotech** [comment]
@SidLeung @eriknyquist please review
@khanning @agdl @facchinm this should fix #280 and #334 
as I mentioned before there is a slight performance impact but it seems more negligeable than I initially though

**Comment by eriknyquist** [comment]
I think I2S, I2SDMA and possibly some more need to set pinMuxMode too. See the following two commits, where I removed them, for reference;

https://github.com/01org/corelibs-arduino101/commit/3d3c1f92c2c15724725f71542bc564754ba5d6e3
https://github.com/01org/corelibs-arduino101/commit/1a5e3f7b2d65cf2b81417f85bd24ca455bdaa1fc

**Comment by agdl** [comment]
Works for me!

**Comment by noelpaz** [comment]
@russmcinnis . Can you please verify?

**Comment by bigdinotech** [comment]
@eriknyquist I2S will be added once the @SidLeung finishes the changes for it

**Comment by russmcinnis** [comment]
I test variations of the examples and it works for me too. I was doing some testing using sketch delayMicroseconds() to just measure the frequency of 100 consecutive digitalRead() or digitalWrite() calls without checking any signals. The digitalWrite() function speed with the mux checking added was about 75% of the speed without it.

**Comment by bigdinotech** [comment]
@russmcinnis please test this with CurieSoftwareSerial library.
It should only affect the tx performance of it and the appropriate changes is already in this commit

**Comment by eriknyquist** [comment]
@russmcinnis can you see what SoftwareSerial behaviour is like with these changes?

**Comment by russmcinnis** [comment]
I don't see any difference. I ran the BAT test that hooks up SoftwareSerial pins to Hardware Serial (Serial1) pins. The test runs a lot of transactions and passes. 

Next I ran most of the baud rates by looping:
  mySerial.write(0x1);
I have some tables of the frequency from the scope and I don't see any difference. I thought I would see a difference since before I was measuring digitalWrite(HIGH and LOW) in a tight loop and saw performance fall by 25%.

**Comment by bigdinotech** [comment]
@calvinatintel please merge this one also. Jenkins merger is also failing for this one

**Pull request merged**
