### PR TITLE
Add virtual beginMulticast(...) stub to UDP class

### PR DESCRIPTION
**Pull request by sandeepmistry**
Port of https://github.com/arduino/Arduino/pull/5796

Please hold off merging until the PR linked above is merged.

### CODE REVIEW

**Comment by sandeepmistry** [comment]
@facchinm has merged this in the main Arduino repo: https://github.com/arduino/Arduino/pull/5796

So this is ready to go now.

**Comment by SidLeung** [comment]
@sandeepmistry , would you please let me know if this PR needed to be merged?  Thanks.

**Comment by sandeepmistry** [comment]
@SidLeung yes please.

**Comment by SidLeung** [comment]
Would you please be kind enough to rebase to 01org/master?  Thanks.

**Comment by sandeepmistry** [comment]
@SidLeung I've rebased it.

**Pull request merged**
