### PR TITLE
shared memory structure changes for CODK-M

### PR DESCRIPTION
**Pull request by bigdinotech**

### CODE REVIEW

**Comment by bigdinotech** [comment]
@eriknyquist please review

**Comment by eriknyquist** [comment]
Almost there. give a little detail in the commit message please-- subject is good now, but some more details below. Like, *what* exactly are the changes (very briefly), and most importantly *why* are these changes needed?

**Comment by bigdinotech** [comment]
@eriknyquist I added the commit message

**Comment by eriknyquist** [comment]
I'm still confused. I don't understand *why* the IPM struct is needed in shared memory?

**Comment by bigdinotech** [comment]
IPM struct is part of CODK-M firmware

**Comment by eriknyquist** [comment]
Approved. Assigning to @bigdinotech for merging, if he's ready for it

**Comment by bigdinotech** [comment]
@eriknyquist @calvinatintel this PR has already been merged by sysmaker

**Comment by eriknyquist** [comment]
OK, close it then

**Pull request closed without merging**
