### PR TITLE
Add support for SPI1 device

### PR DESCRIPTION
**Pull request by eriknyquist**
Add 'SPI1' instance to current SPI library, for accessing the onboard SPI flash. Additionally, tidy up the SPI library code (there is one commit for each. The only functional changes are in the first commit "Add support for SPI1 device to SPIClass").

### CODE REVIEW

**Comment by bigdinotech** [comment]
@calvinatintel looks good. +1

**Comment by eriknyquist** [comment]
@calvinatintel @SidLeung ready for review

**Comment by SidLeung** [comment]
@eriknyquist @bigdinotech Looks good.  May I suggest to use SPI_FOR_FLASH (or something better) in place of SPI1?  I bet someone is going to complain about the flipping of the indexing...

**Comment by eriknyquist** [comment]
@SidLeung, you are right someone will surely complain. The flipped indexing makes things easier to follow if you are also looking at EAS / schematic. However if you are not, then it does not. I'm happy either way, let me know what you think.

**Comment by eriknyquist** [comment]
@SidLeung I think I misunderstood, do you mean change the instance name? so SPI1.begin() becomes SPI_FOR_FLASH.begin() (or whatever)? I think it's good to stick with the way other modules do it, i.e. Serial and Serial1

**Comment by intel-larry** [comment]
For expediency – maybe get it working then sort out the names?

**Comment by SidLeung** [comment]
@eriknyquist @intel-larry @calvinatintel Agree.  Let's get it working first.  Stick with the naming, put a comment that indicating which SPI is for Flash, etc.

**Comment by eriknyquist** [comment]
Sounds good.

**Comment by calvinatintel** [comment]
@eriknyquist Is this ready to be merged?

**Comment by eriknyquist** [comment]
@calvinatintel I'm testing this change today against some SPI flash libraries, let's wait until Monday just in case I find an issue.

**Comment by eriknyquist** [comment]
@SidLeung @bigdinotech @calvinatintel, fixed a bug in the SPISettings class which was preventing the Serial Flash library working out of the box. 3rd commit ready for code review, after which the whole PR can be merged.

**Comment by bigdinotech** [comment]
@calvinatintel looks good. Please merge

**Pull request merged**
