### PR TITLE
Shrink oversized objects in SRAM

### PR DESCRIPTION
**Pull request by eriknyquist**
824 bytes is gained for use by sketches.
@SidLeung @bigdinotech @calvinatintel @russmcinnis @noelpaz please review.

**Please do not merge until it is explicitly requested**

### CODE REVIEW

**Comment by calvinatintel** [comment]
I'm guessing that the updated `.a` was necessary?

**Comment by eriknyquist** [comment]
yes-- I changed files in system/libarc32_arduino101/*

**Comment by eriknyquist** [comment]
Agree-- there will be several rounds of BAT & manual testing on this PR before it gets merged.

**Comment by bbaltz505** [comment]
KW gives a thumbs-up (no new defects). See build: prebuild_48_PR301.

**Comment by noelpaz** [comment]
Internal BAT Tests were ran using tT and 101 boards no issues. +1

**Pull request merged**
