### PR TITLE
Jira566 I2S DMA improvement: add two extra buffer on TX and RX side

### PR DESCRIPTION
**Pull request by linrjing**
@xieqi @sgbhu @SidLeung
Add two extra buffer on TX and RX side because of the padding zero. Code is still in investigation.

### CODE REVIEW

**Comment by bigdinotech** [comment]
@linrjing looks good. But can you please combine it with the existing I2S library?
Just move over the src and examples and combine the keywords.txt
@calvinatintel can you generate a libarc32drv_arduino101.a

**Comment by eriknyquist** [comment]
@linrjing please update commit message accurately describe the changes

**Comment by calvinatintel** [comment]
@eriknyquist How would you title/comment the change? I'm making a new PR with the `libarc32drv_arduino101.a`

**Comment by calvinatintel** [comment]
Replaced by PR https://github.com/01org/corelibs-arduino101/pull/233

**Pull request closed without merging**
