### PR TITLE
AGM-157 Add support for _BV() macro

### PR DESCRIPTION
**Pull request by bigdinotech**
Add support for _BV() macro

### CODE REVIEW

**Comment by bigdinotech** [comment]
@kmsywula @calvinatintel ready for review

**Comment by bigdinotech** [comment]
@kmsywula @SidLeung please review

**Comment by SidLeung** [comment]
@calvinatintel Reviewed.  Ready for merge.

**Comment by calvinatintel** [comment]
Please rebase to the upstream/master

**Comment by calvinatintel** [comment]
Cherry-picked

**Pull request closed without merging**
