### PR TITLE
[DO NOT MERGE YET] Use unified upload tool

### PR DESCRIPTION
**Pull request by facchinm**
By replacing existing `bash` + script procedure (very OS-specific and error prone) with this tool (https://github.com/facchinm/arduino101load) the flasher commandline generation can be greatly simplified.
This would also help separation between legacy `sketchUploader` and dfu-based uploader for 101

### CODE REVIEW

**Comment by bbaltz505** [comment]
Thanks. I'll try it out. So we are only distributing a OS-specific Go binary for the script then? That is much simpler. I suppose a downside is that you can't view and tweak the upload script if you had to.

**Comment by facchinm** [comment]
Right, but the source is very straightforward. 
I also forked the tools repo here (https://github.com/facchinm/intel-arduino101-tools), removing all the edison/galileo related files and retagging to work in the Board manager, if you wish to test it we could merge before the next core release :smile:

**Comment by calvinatintel** [comment]
I like it, but we can't remove the support files like `bash.exe` because Edison and Galileo use them.

**Comment by calvinatintel** [comment]
@facchinm, one of the downside of this approach is that the uploader becomes less user-serviceable compared to a `.sh`. Do you foresee a problem with this?

**Comment by SidLeung** [comment]
I would like to know the original reasoning/purpose of choosing scripting over an utility program/app to invoke the tools.  Is it,
  +  Visibility is important to the end user.
  +  Max flexibility for the end user.
  +  DIY changes for the advance user.
  +  The cheapest and fastest way to get the system going.

If it is the last reasoning, which is very valid, it would be a partial solution.

**Comment by facchinm** [comment]
Thanks for the comments, with this PR and the twin tools repo I tried to resolve a couple of issues
* bash scripts is an hell when handling file paths and complex operations (the original script was broken for paths with spaces and needed a temp file to parse the `dfu` command output)
* there is no need to have different paths for different OS
* Edison/Galileo uploader is 100% different from 101 loader, I see no good reason to have them contained in a single package
The "hackability" of a script is higher, of course, but since the replacement is open source and setting up the go toolchain is a 10 minutes task, it could reach the same objective with a much cleaner implementation

**Comment by calvinatintel** [comment]
@facchinm We like the golang solution, but it might be more suitable for next product. Do you think the current implementation should be replaced by a golang version?

**Comment by bbaltz505** [comment]
Closing this PR as we will not use this tool for Arduino 101. (see PR 104)

**Pull request closed without merging**
