### PR TITLE
Fix arduino101load argument passing if binary path contains spaces

### PR DESCRIPTION
**Pull request by facchinm**
This issue was first reported to the support channel and was solved by the proposed patch

### CODE REVIEW

**Comment by SidLeung** [comment]
@calvinatintel @bigdinotech @eriknyquist , please review the change.  @noelpaz @russmcinnis , please perform verification testing.  Will merge the change to main trunk upon completion.  Targeted for Deneb.

**Comment by calvinatintel** [comment]
This is a fine solution, but I think `{build.path}` should be provided with the spaces escaped from the upstream.

**Comment by facchinm** [comment]
http://forum.arduino.cc/index.php?topic=448542.0 shows the same problem indeed

**Comment by calvinatintel** [comment]
@russmcinnis @noelpaz Please test

**Comment by novashah** [comment]
@russmcinnis @noelpaz Is this tested?

**Comment by noelpaz** [comment]
I tested this by saving the skecth in a folder with spaces in the name pleace note than when I named my Sketch "S P A C E D  Blink", it renamed it into S_P_A_C_E_S__Blink  and the IDE spit out this messgae:

The sketch name had to be modified. Sketch names can only consist
of ASCII characters and numbers (but cannot start with a number).
They should also be less than 64 characters long.

@calvinatintel explained that it is to verify that the enclosing folders that will have spaces. Fix is verified

**Comment by noelpaz** [comment]
@facchinm  -- fix verified. @yashaswini-hanji  -- Please Squash and Merge

**Comment by yashaswini-hanji** [comment]
PR merged

**Pull request closed without merging**
