### PR TITLE
Fix dtostrf rounding strategy

### PR DESCRIPTION
**Pull request by eriknyquist**
I missed a couple of corner cases in my first implementation, which have
now been addressed. First reported in isssue #300.

@bigdinotech @calvinatintel @SidLeung @noelpaz @russmcinnis  please review

**Please do not merge until explicitly requested**

### CODE REVIEW

**Comment by noelpaz** [comment]
Will be testing but logic looks good. Need to test this on negative numbers

**Comment by bbaltz505** [comment]
I believe this works for the reported issue (printing a double) but it doesn't print correctly when the double is cast as a float;
```
void loop() {
  double x = 0.999999999999;
  delay(500);
  Serial.print("double: ");
  Serial.println(x);         // correctly prints 1.0
  Serial.print("float: ");
  Serial.println((float)x);  // prints 2.0
}

**Comment by noelpaz** [comment]
Negative numbers are being converted into positive. I also tested for specifying more places than initial declaration.

`
double x = 0.9999;
double y = -0.9999;
void setup() {
  // put your setup code here, to run once:
  Serial.begin( 9600 );

}

void loop() {
  // put your main code here, to run repeatedly:
  Serial.println(x);
  Serial.println(x, 1);
  Serial.println(x, 2);
  Serial.println(x, 3);
  Serial.println(x, 4);
  Serial.println(x, 5);
  Serial.println("Negative");
  Serial.println(y);
  Serial.println(y, 1);
  Serial.println(y, 2);
  Serial.println(y, 3);
  Serial.println(y, 4);
  Serial.println(y, 5);


  delay(500);
}`

**Comment by noelpaz** [comment]
Also note that in @bbaltz505  example , he gets a 2.0 when he casts it to float, I get 1.0 and the difference is how is number is a bit bigger  0.999999999999; > 0.9999,

**Comment by eriknyquist** [comment]
@noelpaz I fixed the sign problem. @bbaltz505 not really sure what's going on there, need some more time to check it out.

**Comment by eriknyquist** [comment]
@noelpaz @bbaltz505 should be all good now. Please test.

**Comment by bbaltz505** [comment]
Works perfectly now - both, my example and the sample code in issue #300

**Comment by noelpaz** [comment]
Here is  my test code. It is interesting what happens when you specify the precision  When a whole with a fractional part almost 0 vs just a number that is only a fraction and also almost 0

Meaning if x = 0.000000000009  Serial.println(x, 12)   will result in 0.000000000009
vs if x = 1.000000000009 then Serial.println(x, 12) will result in 1.000000000000

The behavior is also in Uno, so

```
void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);

}

void loop() {


  delay(500);
  double x = 0.999999999999;
  Serial.print("double pos almost 1: ");
  Serial.println(x);
  Serial.println(x, 12);
  Serial.println(x, 13);
  Serial.println("float pos almost 1: ");
  Serial.println((float)x);
  Serial.println((float)x, 12);
  Serial.println((float)x, 13);

  x = -0.999999999999;
  Serial.println("double neg almost 1: ");
  Serial.println(x);
  Serial.println(x, 12);
  Serial.println(x, 13);
  Serial.println("float neg almost 1: ");
  Serial.println((float)x);
  Serial.println((float)x, 12);
  Serial.println((float)x, 13);

  //delay(500);
  x = 0.000000000009;
  Serial.println("double pos almost 0: ");
  Serial.println(x);
  Serial.println(x, 12);
  Serial.println(x, 13);
  Serial.println("float pos almost 0: ");
  Serial.println((float)x);
  Serial.println((float)x, 12);
  Serial.println((float)x, 13);
  x = -0.000000000009;
  Serial.println("double neg almost 0: ");
  Serial.println(x);
  Serial.println(x, 12);
  Serial.println(x, 13);
  Serial.println("float neg almost 0: ");
  Serial.println((float)x);
  Serial.println((float)x, 12);
  Serial.println((float)x, 13);


  x = 1.999999999999;
  Serial.println("Whole + double pos almost 1: ");
  Serial.println(x);
  Serial.println(x, 12);
  Serial.println(x, 13);
  Serial.println("Whole + float pos almost 1: ");
  Serial.println((float)x);
  Serial.println((float)x, 12);
  Serial.println((float)x, 13);

  x = -1.999999999999;
  Serial.println("Whole + double neg almost 1: ");
  Serial.println(x);
  Serial.println(x, 12);
  Serial.println(x, 13);
  Serial.println("Whole + float neg almost 1: ");
  Serial.println((float)x);
  Serial.println((float)x, 12);
  Serial.println((float)x, 13);
  //delay(500);
  x = 1.000000000009;
  Serial.println("Whole + double pos almost 0: ");
  Serial.println(x);
  Serial.println(x, 12);
  Serial.println(x, 13);
  Serial.println("Whole + float pos almost 0: ");
  Serial.println((float)x);
  Serial.println((float)x, 12);
  Serial.println((float)x, 13);
  x = -1.000000000009;
  Serial.println("Whole + double neg almost 0: ");
  Serial.println(x);
  Serial.println(x, 12);
  Serial.println(x, 13);
  Serial.println("Whole + float neg almost 0: ");
  Serial.println((float)x);
  Serial.println((float)x, 12);
  Serial.println((float)x, 13);

}
```

**Comment by eriknyquist** [comment]
@noelpaz, these are expected limitations in floating-point representations.

@bbaltz505 I just made one more update. My last change forced `dtostrf` to convert all doubles to floats, losing precision, like Arduino's print function does. But I changed my mind about this, since it breaks `dtostrf` compatibility (DoubleToSTringFloat). So your test sketch that prints '0.99999999' will now print this:

`double : 0.99999999`
`float : 1.00000000`

As it rightly should. Doubles have more precision that floats.

**Comment by bbaltz505** [comment]
Latest update looks good.

**Pull request merged**
