### PR TITLE
SerialFlash: fix compile errors

### PR DESCRIPTION
**Pull request by eriknyquist**
Old SerialFlash directory was still there-- delete it

@facchinm this was partially my fault.... I didn't test your change properly. Please take a look, and verify I wasn't misunderstanding your intentions....

### CODE REVIEW

**Comment by eriknyquist** [comment]
Waiting for confirmation that crc16.h is OK for us to ship with current license-- please don't merge this until I've confirmed it

**Comment by noelpaz** [comment]
Actually it is not a compile error as there is still no INO in the IDE examples and libraries folder. I got the latest 1.8.1 library as well as the latest-nightly built. You will see the error from the libnrary manager complaining about an invalid library.

I will test the new PR to see if the behavior is still there

**Comment by noelpaz** [comment]
I will have to revoke my approval. Since we were not up to speed on the move to SerialFlash and  renamed to CurieSerialFlash, it was not a part of a test suite.

I just compile one of the CurieSerialFlash examples and I am getting  this erroe

`In file included from /Users/<path snipped>/libraries/CurieSerialFlash/examples/CopyFromSerial/CopyFromSerial.ino:64:0:
/Users/nfpaz/Library/Arduino15/packages/Intel-Test/hardware/arc32/0.0.214/libraries/CurieSerialFlash/CurieSerialFlash.h:4:25: fatal error: SerialFlash.h: No such file or directory
 #include "SerialFlash.h"
                         ^`

**Comment by facchinm** [comment]
Hi @eriknyquist ,
my PR was prepared before the merge of https://github.com/01org/corelibs-arduino101/pull/288, hence the stray file in SerialFlash folder; Github resolved the merge conflict in a quite funny way, so it is safe to remove that file/folder.
@noelpaz you need to install SerialFlash by PaulS in order to compile CurieSerialFlash. The intention was to free you from the burden of maintaining a library with very few differences (a couple of defines) from the mainline. We did the same for Adafruit's Neopixel and others.

**Comment by noelpaz** [comment]
@facchinm Thanks.  I also created another PR 468 to temporary fix the comments on the examples comments which currently tell you to use library manager to get the Serial Flash Library. Currently the library manager does no have the correct version that will work and they have to get the latest from Github.

**Comment by eriknyquist** [comment]
@facchinm thanks-- I'm not sure why it wasn't compiling for me without crc16.h. I may have had an old version of the library hanging around. Anyway, working now, and I've removed crc16.h

**Pull request merged**
