### PR TITLE
Make sure LED is not lit on sketch start

### PR DESCRIPTION
**Pull request by bigdinotech**
-The LED retains the last state it was in after a sketch upload
-We need to make sure its is not lit on sketch startup so that behavior
is consistent

### CODE REVIEW

**Comment by bigdinotech** [comment]
@SidLeung @eriknyquist ready for review

**Comment by SidLeung** [comment]
@russmcinnis , @noelpaz , please perform system testing.

**Comment by bigdinotech** [comment]
https://github.com/01org/corelibs-arduino101/commit/2daed478047ff734551afcaddffb27debc352be3

**Comment by sandeepmistry** [comment]
@bigdinotech nice!

Are all the pins in input mode on sketch start? That's the default behaviour of AVR boards like the Uno and we should aim for the same for the 101.

For example, the SAMD core for boards like the Zero and MKR1000 has the following: 

```c
  // Setup all pins (digital and analog) in INPUT mode (default is nothing)
  for (uint32_t ul = 0 ; ul < NUM_DIGITAL_PINS ; ul++ )
  {
    pinMode( ul, INPUT ) ;
  }
```

https://github.com/arduino/ArduinoCore-samd/blob/96745cd48d8232ed37ec03d3a71d510aa9410f38/cores/arduino/wiring.c#L83-L87

cc/ @cmaglie

**Pull request closed without merging**
