### PR TITLE
Add unimplement APIs for BLEDescriptor

### PR DESCRIPTION
**Pull request by sgbihu**
1. Add the descriptor's read feature.
2. Fix the bug when add multi-descriptor
3. Add the comments for APIs 

@SidLeung please help review the code.

### CODE REVIEW

**Comment by eriknyquist** [comment]
@sgbihu please assign reviewers, if you want somebody to review it

**Comment by sgbihu** [comment]
I don't have access to assign the reviewer or add labels.

**Comment by eriknyquist** [comment]
@sgbihu my mistake

**Comment by SidLeung** [comment]
This PR is replaced by #448 and it will be closed.

**Pull request closed without merging**
