### PR TITLE
i2s_dma update

### PR DESCRIPTION
**Pull request by linrjing**
@SidLeung @calvinatintel   a word mistake need to be updated.

### CODE REVIEW

**Comment by bigdinotech** [comment]
Thanks @linrjing.
@calvinatintel is the summary good enough for you?
If so it looks good to me

**Comment by calvinatintel** [comment]
@eriknyquist is our stylist

**Comment by eriknyquist** [comment]
Hi @linrjing, please refer to commit message guidelines [here](https://github.com/01org/corelibs-arduino101/wiki/Writing-a-commit-message). Specifically, If you could rewrite the message to describe your changes, e.g. "CurieI2SDMA.h: Fix typo", we would appreciate it!

**Comment by linrjing** [comment]
Hi @eriknyquist, the commit message has been amended.

**Comment by eriknyquist** [comment]
@linrjing thank you. @calvinatintel +1

**Comment by eriknyquist** [comment]
@linrjing actually not quite. While ammending the commit you also added a new change that was not there originally (the comment at line 76 in I2SDMA_RXCallBack.ino).

Additionally, this comment is quite confusing; it does not really help in the understanding of the code that follows, and it will only confuse inexperienced users (I'm experienced and it confused me...).

If you feel the need to explain this block of code with a comment, then I agree that this is a good thing to do, but just remember you are writing for inexperienced users. Pretend you are explaining to a child, not an experienced developer.

**Comment by linrjing** [comment]
Hi @eriknyquist ,thanks for your help. The commit has been amended. More detail explanatory notes for the I2SDMA_RXCallBack.ino codes has been added.

**Comment by eriknyquist** [comment]
@linrjing thank you, it looks OK now. @calvinatintel go ahead and merge.

**Comment by calvinatintel** [comment]
cherry-picked

**Comment by eriknyquist** [comment]
Github prettified the commit message and fooled me into thinking your message was formatted correctly. It's not. That's my fault for not spotting it. @linrjing please refer to our commit message guidelines in future, I posted the link in an earlier comment but here it is again just in case: https://github.com/01org/corelibs-arduino101/wiki/Writing-a-commit-message

Specifically, you must always leave the 2nd line blank. Type `git log --oneline` inside a local version that contains this commit, and you will see why this convention exists.

**Comment by linrjing** [comment]
Sorry, @eriknyquist. After I type "git log --oneline", I found the <description:> was at the same line with <subject:>.  When I amended the commit, I should have add a blank line after <subject:> line. Currently what can I do? The codes has been merged.

**Comment by eriknyquist** [comment]
@linrjing it's fine, like you said it's already merged.  Can't do anything without re-writing the public history, which is a bad idea. No worries, just remember the guidelines next time please!

**Pull request closed without merging**
