### PR TITLE
Jira 832 Sample Sketch to exercise the BLEbroadcast option.

### PR DESCRIPTION
**Pull request by sgbihu**
1. Add example sketch
    libraries/CurieBLE/examples/peripheral/broadcast

### CODE REVIEW

**Comment by SidLeung** [comment]
@sgbihu , I think you are using the sketch from Don Coleman @ gitHub.  I am asking him to put in a licensing header before we pull it in as part of the CoreLibs release.

@calvinatintel , @yashaswini-hanji , is there a procedure to take sketch from GItHub and use it in our coreLibs?  I suppose we just need the proper licensing.  Am I correct?

**Comment by calvinatintel** [comment]
What's the license of the original sketch? Can you give me a link to it?

**Comment by SidLeung** [comment]
@calvinatintel , @yashaswini-hanji ,  it is code from someone's gitHub request,

https://github.com/01org/corelibs-arduino101/issues/420

I did ask him for licensing.  Please check out the end of the threat.

**Comment by SidLeung** [comment]
In light of the fact that the sample sketch is not public, another PR without the sample sketch is generated,

https://github.com/01org/corelibs-arduino101/pull/438

This PR will be closed.

**Comment by SidLeung** [comment]
This PR is replaced by #438.

**Comment by noelpaz** [comment]
I tested the sketch and the way to test this in NRF is to just scan but you cannot connect and do not connect. You should see the Service data incrementing.

The caveat is that if you central app stops scanning then the Service data will stop. Just refresh the scan and you should see the incrementing value.

**Pull request closed without merging**
