### PR TITLE
Fixes to pass validation with test suite

### PR DESCRIPTION
**Pull request by facchinm**
This is needed to pass C++ validation in test suite

### CODE REVIEW

**Comment by calvinatintel** [comment]
@SidLeung @kmsywula @intel-larry Please review

**Comment by facchinm** [comment]
I've added two more commits to address issues emerged with recently added tests.
Also changed the PR title to reflect the expanding collection of commits

**Comment by calvinatintel** [comment]
@SidLeung @kmsywula @bigdinotech Please review

**Comment by bigdinotech** [comment]
@calvinatintel looks good to me. +1

**Pull request merged**
