### PR TITLE
Change upload tool and automatically update BLE FW

### PR DESCRIPTION
**Pull request by facchinm**
This PR works in conjuntion with https://github.com/facchinm/arduino101load/. 
The updated dependencies for the json are
```
            {
              "packager": "Intel",
              "version": "1.6.9+1.0.1",
              "name": "arc-elf32"
            },
            {
              "packager": "Intel",
              "version": "2.0.0",
              "name": "arduino101load"
            },
            {
              "packager": "Intel",
              "version": "0.9.0+0.1",
              "name": "openocd"
            },
            {
              "packager": "arduino",
              "version": "0.9.0-arduino1",
              "name": "dfu-util"
            }
```

Please take a look before releasing 2.0.1; flashing the x86 RTOS FW is disabled in this PR but can be re-enabled at any time

@SidLeung @calvinatintel @sandeepmistry @eriknyquist

### CODE REVIEW

**Comment by SidLeung** [comment]
@bigdinotech , would you please review the changes.  Would like to merge them to main trunk so that @russmcinnis and @noelpaz can start testing x86 image download.  Thanks.

**Comment by SidLeung** [comment]
Tacked by Jira 888.

**Comment by noelpaz** [comment]
@facchinm . I have a question. I added the files from https://github.com/facchinm/arduino101load/ into my arduino101 load folder but I am getting this error. I check the file permissions and it is okay. Any ideas?

`
"/Users/nfpaz/Library/Arduino15/packages/Intel-Test/tools/arc-elf32/1.6.9+1.0.1/bin/arc-elf32-gcc" -nostartfiles -nodefaultlibs -nostdlib -static -Wl,-X -Wl,-N -Wl,-mcpu=quarkse_em -Wl,-marcelf -Wl,--gc-sections "-T/Users/nfpaz/Library/Arduino15/packages/Intel-Test/hardware/arc32/0.0.219/variants/arduino_101/linker_scripts/flash.ld" "-Wl,-Map,/var/folders/gx/sr9tmyg95_932b_vgf44sr3c0000gq/T/arduino_build_789891/Blink.ino.map"  -o "/var/folders/gx/sr9tmyg95_932b_vgf44sr3c0000gq/T/arduino_build_789891/Blink.ino.elf" "-L/var/folders/gx/sr9tmyg95_932b_vgf44sr3c0000gq/T/arduino_build_789891" "-L/Users/nfpaz/Library/Arduino15/packages/Intel-Test/hardware/arc32/0.0.219/variants/arduino_101" -Wl,--whole-archive "-larc32drv_arduino101" -Wl,--no-whole-archive -Wl,--start-group "-larc32drv_arduino101" -lnsim -lc -lm -lgcc "/var/folders/gx/sr9tmyg95_932b_vgf44sr3c0000gq/T/arduino_build_789891/sketch/Blink.ino.cpp.o" "/var/folders/gx/sr9tmyg95_932b_vgf44sr3c0000gq/T/arduino_build_789891/core/variant.cpp.o" "/var/folders/gx/sr9tmyg95_932b_vgf44sr3c0000gq/T/arduino_build_789891/core/core.a"
/Users/nfpaz/Library/Arduino15/packages/Intel-Test/tools/arduino101load/0.0.219/arduino101load -c -from="/var/folders/gx/sr9tmyg95_932b_vgf44sr3c0000gq/T/arduino_build_789891/Blink.ino.elf" -to="/var/folders/gx/sr9tmyg95_932b_vgf44sr3c0000gq/T/arduino_build_789891/../arduino101_sketch.debug.elf"
fork/exec /Users/nfpaz/Library/Arduino15/packages/Intel-Test/tools/arduino101load/0.0.219/arduino101load: permission denied
`

**Comment by facchinm** [comment]
Does `/Users/nfpaz/Library/Arduino15/packages/Intel-Test/tools/arduino101load/0.0.219/arduino101load` executable exists?

**Comment by noelpaz** [comment]
Yes, But but I was wondering if I have to rebuild arduino101load with go? If you have a Mac and can zip it that will be good. I haven't built it for a long time and not set up.

**Comment by facchinm** [comment]
You can use this precompiled package (http://downloads.arduino.cc/tools/arduino101load-2.0.0-darwin_amd64.tar.bz2) or rebuild it by yourself, it should work in both cases

**Comment by noelpaz** [comment]
Martino I am still getting the same error. Something with fork/exec. I also made sure that /var/folders/gx is world accesible i.e chmod 777

fork/exec /Users/nfpaz/Library/Arduino15/packages/Intel-Test/tools/arduino101load/0.0.219/arduino101load: permission denied
Error compiling for board Arduino/Genuino 101.

The arduino10load  output:

`nfpaz-mac01:arduino101load nfpaz$ ./arduino101load 
Starting download script...
Need to specify dfu-util location`

**Comment by noelpaz** [comment]
So it looks like it cannot find this file arduino101_sketch.debug.elf  ,, I look for that file in the corelibs . In 1.0.7 the file link by Arduino101 load is a .hex file

**Comment by noelpaz** [comment]
@facchinm . I created a JSON using our internal path names and I think I need to get the JSON that you created. Not sure how we are going to replicate it inside our jenkins to match what is working for you. We may have to involve @yashaswini-hanji 

My JSON looks like this
```
"toolsDependencies": [
                    {
                        "packager": "Intel-Test",
                        "version": "0.0.222",
                        "name": "arduino101load"
                    },
                    {
                        "packager": "Intel-Test",
                        "version": "1.6.9+1.0.1",
                        "name": "arc-elf32"
                    },
                    {
                        "packager": "Intel-Test",
                        "version": "0.9+0.1",
                        "name": "openocd"
                    },
                    {
                        "packager": "Intel-Test",
                        "version": "2.0.0",
                        "name": "flashpack"
                    }
                ],
```

**Comment by noelpaz** [comment]
Also if I run the command in the terminal
```
/arduino101load -c -from="/var/folders/gx/sr9tmyg95_932b_vgf44sr3c0000gq/T/arduino_build_352232/Blink.ino.elf" -to="/var/folders/gx/sr9tmyg95_932b_vgf44sr3c0000gq/T/arduino_build_352232/../arduino101_sketch.debug.elf"
```
I do not get any errors

**Comment by facchinm** [comment]
Hi Noel, 
I'm really bugged by this behaviour but I couldn't reproduce it in any way... 
In fact, your json is missing the dfu-utils dependency (which is compulsory with this uploader); this could be the underlying problem but I'm not 100% sure.
I'm pasting here my json (which uses this PR core)  and the verbose output on OSX, so we can check the differences.

```json
        {
          "name": "Intel Curie Boards",
          "version": "2.0.1",
          "category": "Arduino Certified",
          "archiveFileName": "corelibs-arduino101-2.0.1-tools.zip",
          "architecture": "arc32",
          "url": "https://github.com/facchinm/corelibs-arduino101/archive/2.0.1+tools.zip",
          "checksum": "SHA-256:b5f3c92b51681f5589334b5c771d0741ff4a2678f43fbbcec7b8a0e946420a3e",
          "size": 6256714,
          "boards": [
            {
              "name": "Arduino/Genuino 101"
            }
          ],
          "toolsDependencies": [
            {
              "packager": "Intel",
              "version": "1.6.9+1.0.1",
              "name": "arc-elf32"
            },
            {
              "packager": "Intel",
              "version": "2.0.0",
              "name": "arduino101load"
            },
            {
              "packager": "Intel",
              "version": "0.9.0+0.1",
              "name": "openocd"
            },
            {
              "packager": "arduino",
              "version": "0.9.0-arduino1",
              "name": "dfu-util"
            }
          ]
        }
```

```
Arduino: 1.6.12 (Mac OS X), Board: "Arduino/Genuino 101"

/Users/test/Downloads/Arduino.app/Contents/Java/arduino-builder -dump-prefs -logger=machine -hardware /Users/test/Downloads/Arduino.app/Contents/Java/hardware -hardware /Users/test/Library/Arduino15/packages -tools /Users/test/Downloads/Arduino.app/Contents/Java/tools-builder -tools /Users/test/Downloads/Arduino.app/Contents/Java/hardware/tools/avr -tools /Users/test/Library/Arduino15/packages -built-in-libraries /Users/test/Downloads/Arduino.app/Contents/Java/libraries -libraries /Users/test/Documents/Arduino/libraries -fqbn=Intel:arc32:arduino_101 -ide-version=10612 -build-path /var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051 -warnings=none -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduino101load.path=/Users/test/Library/Arduino15/packages/Intel/tools/arduino101load/2.0.0 -prefs=runtime.tools.dfu-util.path=/Users/test/Library/Arduino15/packages/arduino/tools/dfu-util/0.9.0-arduino1 -prefs=runtime.tools.arc-elf32.path=/Users/test/Library/Arduino15/packages/Intel/tools/arc-elf32/1.6.9+1.0.1 -prefs=runtime.tools.openocd.path=/Users/test/Library/Arduino15/packages/Intel/tools/openocd/0.9.0+0.1 -verbose /var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/untitled1371460686.tmp/sketch_mar22a/sketch_mar22a.ino
/Users/test/Downloads/Arduino.app/Contents/Java/arduino-builder -compile -logger=machine -hardware /Users/test/Downloads/Arduino.app/Contents/Java/hardware -hardware /Users/test/Library/Arduino15/packages -tools /Users/test/Downloads/Arduino.app/Contents/Java/tools-builder -tools /Users/test/Downloads/Arduino.app/Contents/Java/hardware/tools/avr -tools /Users/test/Library/Arduino15/packages -built-in-libraries /Users/test/Downloads/Arduino.app/Contents/Java/libraries -libraries /Users/test/Documents/Arduino/libraries -fqbn=Intel:arc32:arduino_101 -ide-version=10612 -build-path /var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051 -warnings=none -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduino101load.path=/Users/test/Library/Arduino15/packages/Intel/tools/arduino101load/2.0.0 -prefs=runtime.tools.dfu-util.path=/Users/test/Library/Arduino15/packages/arduino/tools/dfu-util/0.9.0-arduino1 -prefs=runtime.tools.arc-elf32.path=/Users/test/Library/Arduino15/packages/Intel/tools/arc-elf32/1.6.9+1.0.1 -prefs=runtime.tools.openocd.path=/Users/test/Library/Arduino15/packages/Intel/tools/openocd/0.9.0+0.1 -verbose /var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/untitled1371460686.tmp/sketch_mar22a/sketch_mar22a.ino
Using board 'arduino_101' from platform in folder: /Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1
Using core 'arduino' from platform in folder: /Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1
Detecting libraries used...
"/Users/test/Library/Arduino15/packages/Intel/tools/arc-elf32/1.6.9+1.0.1/bin/arc-elf32-g++" -c -mcpu=quarkse_em -mlittle-endian -g -Os -Wall -fno-reorder-functions -fno-asynchronous-unwind-tables -fno-omit-frame-pointer -fno-defer-pop -Wno-unused-but-set-variable -Wno-main -ffreestanding -fno-stack-protector -mno-sdata -ffunction-sections -fdata-sections -fsigned-char  -fno-rtti -fno-exceptions -fcheck-new -D__ARDUINO_ARC__ -std=c++11 -DCONFIG_BLUETOOTH_PERIPHERAL -DCONFIG_BLUETOOTH_CENTRAL -DCONFIG_BLUETOOTH_GATT_CLIENT -w -x c++ -E -CC -DF_CPU=32000000L -DARDUINO=10612 -DARDUINO_ARC32_TOOLS -DARDUINO_ARCH_ARC32 -D__CPU_ARC__ -DCLOCK_SPEED=32 -DCONFIG_SOC_GPIO_32 -DCONFIG_SOC_GPIO_AON -DINFRA_MULTI_CPU_SUPPORT -DCFW_MULTI_CPU_SUPPORT -DHAS_SHARED_MEM "-I/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/system/libarc32_arduino101/common" "-I/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/system/libarc32_arduino101/drivers" "-I/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/system/libarc32_arduino101/bootcode" "-I/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/system/libarc32_arduino101/framework/include"  "-I/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/cores/arduino" "-I/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/variants/arduino_101" "/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/sketch/sketch_mar22a.ino.cpp" -o "/dev/null"
Generating function prototypes...
"/Users/test/Library/Arduino15/packages/Intel/tools/arc-elf32/1.6.9+1.0.1/bin/arc-elf32-g++" -c -mcpu=quarkse_em -mlittle-endian -g -Os -Wall -fno-reorder-functions -fno-asynchronous-unwind-tables -fno-omit-frame-pointer -fno-defer-pop -Wno-unused-but-set-variable -Wno-main -ffreestanding -fno-stack-protector -mno-sdata -ffunction-sections -fdata-sections -fsigned-char  -fno-rtti -fno-exceptions -fcheck-new -D__ARDUINO_ARC__ -std=c++11 -DCONFIG_BLUETOOTH_PERIPHERAL -DCONFIG_BLUETOOTH_CENTRAL -DCONFIG_BLUETOOTH_GATT_CLIENT -w -x c++ -E -CC -DF_CPU=32000000L -DARDUINO=10612 -DARDUINO_ARC32_TOOLS -DARDUINO_ARCH_ARC32 -D__CPU_ARC__ -DCLOCK_SPEED=32 -DCONFIG_SOC_GPIO_32 -DCONFIG_SOC_GPIO_AON -DINFRA_MULTI_CPU_SUPPORT -DCFW_MULTI_CPU_SUPPORT -DHAS_SHARED_MEM "-I/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/system/libarc32_arduino101/common" "-I/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/system/libarc32_arduino101/drivers" "-I/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/system/libarc32_arduino101/bootcode" "-I/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/system/libarc32_arduino101/framework/include"  "-I/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/cores/arduino" "-I/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/variants/arduino_101" "/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/sketch/sketch_mar22a.ino.cpp" -o "/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/preproc/ctags_target_for_gcc_minus_e.cpp"
"/Users/test/Downloads/Arduino.app/Contents/Java/tools-builder/ctags/5.8-arduino10/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/preproc/ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
"/Users/test/Library/Arduino15/packages/Intel/tools/arc-elf32/1.6.9+1.0.1/bin/arc-elf32-g++" -c -mcpu=quarkse_em -mlittle-endian -g -Os -Wall -fno-reorder-functions -fno-asynchronous-unwind-tables -fno-omit-frame-pointer -fno-defer-pop -Wno-unused-but-set-variable -Wno-main -ffreestanding -fno-stack-protector -mno-sdata -ffunction-sections -fdata-sections -fsigned-char -MMD -fno-rtti -fno-exceptions -fcheck-new -D__ARDUINO_ARC__ -std=c++11 -DCONFIG_BLUETOOTH_PERIPHERAL -DCONFIG_BLUETOOTH_CENTRAL -DCONFIG_BLUETOOTH_GATT_CLIENT -DF_CPU=32000000L -DARDUINO=10612 -DARDUINO_ARC32_TOOLS -DARDUINO_ARCH_ARC32 -D__CPU_ARC__ -DCLOCK_SPEED=32 -DCONFIG_SOC_GPIO_32 -DCONFIG_SOC_GPIO_AON -DINFRA_MULTI_CPU_SUPPORT -DCFW_MULTI_CPU_SUPPORT -DHAS_SHARED_MEM "-I/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/system/libarc32_arduino101/common" "-I/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/system/libarc32_arduino101/drivers" "-I/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/system/libarc32_arduino101/bootcode" "-I/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/system/libarc32_arduino101/framework/include"  "-I/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/cores/arduino" "-I/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/variants/arduino_101" "/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/sketch/sketch_mar22a.ino.cpp" -o "/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/sketch/sketch_mar22a.ino.cpp.o"
.....
.....
"/Users/test/Library/Arduino15/packages/Intel/tools/arc-elf32/1.6.9+1.0.1/bin/arc-elf32-gcc" -nostartfiles -nodefaultlibs -nostdlib -static -Wl,-X -Wl,-N -Wl,-mcpu=quarkse_em -Wl,-marcelf -Wl,--gc-sections "-T/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/variants/arduino_101/linker_scripts/flash.ld" "-Wl,-Map,/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/sketch_mar22a.ino.map"  -o "/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/sketch_mar22a.ino.elf" "-L/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051" "-L/Users/test/Library/Arduino15/packages/Intel/hardware/arc32/2.0.1/variants/arduino_101" -Wl,--whole-archive "-larc32drv_arduino101" -Wl,--no-whole-archive -Wl,--start-group "-larc32drv_arduino101" -lnsim -lc -lm -lgcc "/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/sketch/sketch_mar22a.ino.cpp.o" "/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/core/variant.cpp.o" "/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/core/core.a"
/Users/test/Library/Arduino15/packages/Intel/tools/arduino101load/2.0.0/arduino101load -c -from="/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/sketch_mar22a.ino.elf" -to="/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/../arduino101_sketch.debug.elf"
"/Users/test/Library/Arduino15/packages/Intel/tools/arc-elf32/1.6.9+1.0.1/bin/arc-elf32-objcopy" -S -O binary -R .note -R .comment -R COMMON -R .eh_frame  "/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/sketch_mar22a.ino.elf" "/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/sketch_mar22a.ino.bin"
"/Users/test/Library/Arduino15/packages/Intel/tools/arc-elf32/1.6.9+1.0.1/bin/arc-elf32-strip" "/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/sketch_mar22a.ino.elf"
"/Users/test/Library/Arduino15/packages/Intel/tools/arc-elf32/1.6.9+1.0.1/bin/arc-elf32-objcopy" -S -O ihex -R .note -R .comment -R COMMON -R .eh_frame  "/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/sketch_mar22a.ino.elf" "/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/sketch_mar22a.ino.hex"

Sketch uses 48,164 bytes (30%) of program storage space. Maximum is 155,648 bytes.
/Users/test/Library/Arduino15/packages/Intel/tools/arduino101load/2.0.0/arduino101load -dfu="/Users/test/Library/Arduino15/packages/arduino/tools/dfu-util/0.9.0-arduino1" -bin="/var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/sketch_mar22a.ino.bin" -port=COM1 -v -ble_fw_str="ATP1BLE00R-1631C4439" -ble_fw_pos=169984 -rtos_fw_str="" -rtos_fw_pos=0 -core=2.0.0 
arduino101load 2.0.0 - compiled with go1.7.5
Starting download script...
Serial Port: COM1
BIN FILE /var/folders/5t/4k08sf41781_m9tr20gws3h40000gp/T/arduino_build_48051/sketch_mar22a.ino.bin
```

**Comment by noelpaz** [comment]
@facchinm . if you can give me your full JSON and if the sources are public, then I can probably download that way . I do not think we have a dfu-util section, we have flashback instead, which has the dfu-util embedded. If we cannot get to the sources in your json maybe you can zip it up. We need to ask our build person to create the other sections. I thought this was just a change in corelibs. I think I understand where the issue is. Thanks. I hope you get this before your day ends.

**Comment by facchinm** [comment]
Hi @noelpaz , I'm publishing the core in https://downloads.arduino.cc/packages/package_arduino101_2.0.1_index.json . 

With this PR the flashpack is replaced by `arduino101loader` and `dfu-utils` becomes a standalone tool, shared with other platforms.

I understand that the flashpack is part of your standard infrastructure but since it uses bash (or, worse, bat) scripts it is prone to all the errors we had in the past with paths with spaces and similar.  Since its only task in the Arduino world is flashing the firmwares, it's safer to replace it with the actual loader (IMO)

**Comment by noelpaz** [comment]
Thanks Martino @facchinm.

BTW we are working on this, but even before uploading or fw flashing the compilation is not even happening because of the fork\exec error. I built arduinoload on linux 64 and even there with less acl drama like in OSX - I did not expect this permission issue. When I researched it, it seems that writing in temp folders is problematic in go. I am very green in go.

Anyway here is the Linux error

```
/home/nfpaz/.arduino15/packages/Intel-Test/tools/arduino101load/0.0.219/arduino101load -c -from="/tmp/arduino_build_623189/sketch_mar22a.ino.elf" -to="/tmp/arduino_build_623189/../arduino101_sketch.debug.elf"
fork/exec /home/nfpaz/.arduino15/packages/Intel-Test/tools/arduino101load/0.0.219/arduino101load: permission denied
Error compiling for board Arduino/Genuino 101.
```

**Comment by noelpaz** [comment]
@facchinm @SidLeung @yashaswini-hanji ...

I think I found the culprit. On Linux and MacOSX,,, if you place arduino101load binary  on the folder enclosing the folder arduino101load which is also called arduino101load . Of course because linux or mac doesn't require a file name extension you cannot put arduino101load binary alongside a folder called arduino101load. So it looks like we have a path problem and we have to investigate why. It now works for compile  with my workaround  but it is now failing on the upload. I also copied the firmwares folder but we are getting this failure:

```
/Users/nfpaz/Library/Arduino15/packages/Intel-Test/tools/arduino101load/0.0.219/arduino101load -dfu="{runtime.tools.dfu-util.path}" -bin="/Users/nfpaz/tmp/Blink.ino.bin" -port=/dev/cu.usbmodem1421 -v -ble_fw_str="ATP1BLE00R-1631C4439" -ble_fw_pos=169984 -rtos_fw_str="" -rtos_fw_pos=0 -core=2.0.0 
arduino101load 2.0.0 - compiled with go1.8
Starting download script...
Serial Port: /dev/cu.usbmodem1421
BIN FILE /Users/nfpaz/tmp/Blink.ino.bin
Waiting for device...
exec: not started
An error occurred while uploading the sketch
```

**Comment by noelpaz** [comment]
I also tried burn bootloader and we get this error.

```
Users/nfpaz/Library/Arduino15/packages/Intel-Test/tools/arduino101load/0.0.219/arduino101load -dfu="{runtime.tools.dfu-util.path}/x86/bin" -port=/dev/cu.usbmodem1421 -v -force -core=2.0.0 
flag provided but not defined: -force
Usage of /Users/nfpaz/Library/Arduino15/packages/Intel-Test/tools/arduino101load/0.0.219/arduino101load:
  -bin string
    	Location of sketch binary
  -ble_fw_pos int
    	BLE FW ID offset
  -ble_fw_str string
    	BLE FW ID string
  -c	Copy bin_file to bin_save
  -core string
    	Core version
  -dfu string
    	Location of dfu-util binaries
  -f	Force firmware update
  -from string
    	Original file location
  -port string
    	Upload serial port
  -q	Show quiet logging (default true)
  -rtos_fw_pos int
    	RTOS FW ID offset
  -rtos_fw_str string
    	RTOS FW ID string
  -to string
    	Save file location
  -v	Show verbose logging
Error while burning bootloader.

```

**Comment by facchinm** [comment]
Hi Noel, would you mind installing the core I provided via json? It simply places all the files in the right folders and, most important, provides the referenced tools, so variables like `{runtime.tools.dfu-util.path}` get expanded correctly. We can setup a video call if you are still encountering issues after this action :wink:

**Comment by noelpaz** [comment]
@facchinm . The JSON is incomplete.  It looks likw the other section has been trimmed off.

**Comment by facchinm** [comment]
It's not incomplete, it's an overlay over the standard json. You need to add it to the "Additional json" in IDE's preferences, then select Curie boards and install core 2.0.1.
I just tested it on a clean machine and it works just fine

**Comment by noelpaz** [comment]
@facchinm Thanks. I am used to our JSON, but realized this is actually an official Arduino JSON. Anyway we tested with this one and it works. We did discover some other folder and file changes that we where unaware of from 2.0.0 and 1.0.7  in the tools directory. You see we do not test the changes directly on package/Intel  and we now must reflect these changes. I will now leave it to @yashaswini-hanji and @SidLeung  to work with you on this.

**Comment by yashaswini-hanji** [comment]
@noelpaz @russmcinnis could you please test PR475 with http://mkfs.ndg.intel.com/precommit/json/package_0.0.6_index.json

**Comment by yashaswini-hanji** [comment]
@russmcinnis @noelpaz : burn bootloader issue is fixed by Martino and new JSON is created http://mkfs.ndg.intel.com/precommit/json/package_0.0.7_index.json Please use this for testing.

**Comment by yashaswini-hanji** [comment]
Russ confirmed testing completed. Merging PR now

**Pull request merged**
