### PR TITLE
Added setValue for strings

### PR DESCRIPTION
**Pull request by agdl**
This fix allows to use setValue() for const char\* variables

### CODE REVIEW

**Comment by kitsunami** [comment]
Can you provide the context for this?

**Comment by agdl** [comment]
Yes of course:
```
BLECharacteristic stringCharacteristic("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", BLERead | BLEWrite | BLENotify, MAX_LENGTH);
...
...
...
void myTestFunction(){
  char testString[] = "This is a test";
  stringCharacteristic.setValue(testString);
}
```

or something like:

```
BLECharacteristic stringCharacteristic("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", BLERead | BLEWrite | BLENotify, MAX_LENGTH);
...
...
...
void myTestFunction(){
 String testString = "Value is: " + thisValue;
  stringCharacteristic.setValue(testString.c_str());
}
```

**Comment by SidLeung** [comment]
The BLE library is undergo improvement.  Will add in this change as part of the modification.  Please note that "notification" is limited to 20 byte long.  If the string you are sending out is longer than 20 byte, you may have to send it out in 20 byte segments.  In that case, you can consider using an index pointer to walk down the string and specify the segment size for each setValue() call.  You definitely do not want to just call setValue( myLongString );

**Comment by eriknyquist** [comment]
The change looks fine to me, but I'm not sure if it's a necessary one. @SidLeung the BLE master what do you think?

**Comment by sandeepmistry** [comment]
This is one of the API's that I forgot to port from [BLEPeripheral](https://github.com/sandeepmistry/arduino-BLEPeripheral). It makes it much nicer for setting a string value for the characteristic vs `characteristic.setValue(str, strlen(str))`. @agdl noticed it and created this PR to port it over.

More info. at: https://github.com/sandeepmistry/arduino-BLEPeripheral/blob/master/API.md#set-value

**Comment by SidLeung** [comment]
PR #461 addresses this issue.  Will be in the next release.  Please review and close.

**Pull request closed without merging**
